const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function harness(search=''){
 const elements={};for(const id of ['designVersion','designTheme','designOpaque','designViewport','designScope'])elements[id]={value:id==='designVersion'?'baseline':'light',checked:false,disabled:false,handlers:{},addEventListener(t,f){this.handlers[t]=f;}};
 const panel={className:'',setAttribute(){},querySelector(s){return elements[s.slice(1)];}};
 const root={dataset:{}},events={},docEvents={},pending=[],surfaces=Object.fromEntries(['task','system','topMenu','launcher','lock','sleep','toast','gestureToast','wallpaper'].map(id=>[id,{dataset:{}}]));let mounts=0,current='SYS-01';
 const context={URLSearchParams,queueMicrotask:f=>pending.push(f),location:{search},document:{addEventListener(t,f){docEvents[t]=f;},querySelectorAll(){return [];},documentElement:root,createElement(){mounts++;return panel;},getElementById:id=>surfaces[id],querySelector:selector=>selector==='#screen > .wallpaper'?surfaces.wallpaper:{after(){}}},Suite:{current(){return{id:current};}},window:{UI_CATALOG:JSON.parse(fs.readFileSync('src/data/screens.json','utf8')),addEventListener(t,f){events[t]=f;}}};
 vm.runInNewContext(fs.readFileSync('src/js/design-preview.js','utf8'),context);
 const change=(id,value)=>{const e=elements[id];if(typeof value==='boolean')e.checked=value;else e.value=value;e.handlers.change({target:e});};
 return{root,elements,events,change,mounts,pending,preference:value=>docEvents.click({target:{closest:()=>({dataset:{designPreference:value}})}}),surfaces,setCurrent:id=>{current=id;},flush:()=>{while(pending.length)pending.shift()();}};
}
test('V4 presentation is opt-in; baseline remains default',()=>{const h=harness();assert.equal(h.root.dataset.design,'baseline');assert.equal(h.elements.designTheme.disabled,true);});
test('V4 theme and opaque controls do not require any business-state or storage API',()=>{const h=harness('?design=v4');h.change('designTheme','dark');h.change('designOpaque',true);assert.equal(h.root.dataset.designTheme,'dark');assert.equal(h.root.dataset.designOpaque,'true');assert.equal(h.root.dataset.designSample,'true');assert.equal(h.mounts,1);});
test('route changes leave non-sample pages clearly outside V4',()=>{const h=harness('?design=v4');h.events['design:route']({detail:{id:'UNKNOWN-01'}});assert.equal(h.root.dataset.designSample,'false');assert.match(h.elements.designScope.textContent,/保留 V3/);h.events['design:route']({detail:{id:'DAY-05'}});assert.equal(h.root.dataset.designSample,'true');});
test('rollback removes sample styling without navigation or state reset',()=>{const h=harness('?design=v4');for(let i=0;i<30;i++)h.change('designTheme',i%2?'light':'dark');h.change('designVersion','baseline');assert.equal(h.root.dataset.designSample,'false');assert.equal(h.root.dataset.design,'baseline');assert.equal(h.mounts,1);});

test('D1 single-file payload stays within the declared 300000-byte budget',()=>{assert.ok(fs.statSync('dist/index.html').size<=300000);});

test('visibility sync coalesces and follows the final visible surface',()=>{const h=harness('?design=v4');h.setCurrent('UNKNOWN-01');h.events['ui:visibility']();h.events['ui:visibility']();assert.equal(h.pending.length,1);h.flush();assert.equal(h.root.dataset.designSample,'false');h.setCurrent('SYS-01');h.events['ui:visibility']();h.flush();assert.equal(h.root.dataset.designSample,'true');});

test('system foreground never changes the mounted task presentation',()=>{const h=harness('?design=v4');h.events['design:route']({detail:{id:'DAY-05'}});for(const id of ['SYS-04','SYS-06','SYS-05','SYS-01','SYS-03']){h.setCurrent(id);h.events['ui:visibility']();h.flush();assert.equal(h.surfaces.task.dataset.designRoute,'DAY-05');assert.equal(h.surfaces.task.dataset.designSample,'true');}assert.equal(h.surfaces.topMenu.dataset.designSample,'true');assert.equal(h.surfaces.lock.dataset.designSample,'true');assert.equal(h.surfaces.sleep.dataset.designSample,'true');assert.equal(h.surfaces.launcher.dataset.designSample,'true');});
test('sample home cannot migrate a mounted non-sample task',()=>{const h=harness('?design=v4');h.events['design:route']({detail:{id:'UNKNOWN-01'}});h.setCurrent('SYS-01');h.events['ui:visibility']();h.flush();assert.equal(h.surfaces.system.dataset.designSample,'true');assert.equal(h.surfaces.task.dataset.designRoute,'UNKNOWN-01');assert.equal(h.surfaces.task.dataset.designSample,'false');});
test('target task presentation is ready synchronously before its render',()=>{const h=harness('?design=v4');h.events['design:route']({detail:{id:'DAY-05'}});assert.equal(h.surfaces.task.dataset.designRoute,'DAY-05');assert.equal(h.surfaces.task.dataset.designSample,'true');assert.equal(h.pending.length,0);});
test('theme, material, and V3 rollback apply independently to every surface',()=>{const h=harness('?design=v4');h.events['design:route']({detail:{id:'DAY-05'}});h.change('designTheme','dark');h.change('designOpaque',true);for(const surface of Object.values(h.surfaces)){assert.equal(surface.dataset.designTheme,'dark');assert.equal(surface.dataset.designOpaque,'true');assert.equal(surface.dataset.designSurface,'true');}h.change('designVersion','baseline');for(const surface of Object.values(h.surfaces))assert.equal(surface.dataset.designSample,'false');assert.equal(h.surfaces.task.dataset.designRoute,'DAY-05');});

test('all 86 registered routes participate in the D3 presentation candidate',()=>{const h=harness('?design=v4');const routes=JSON.parse(fs.readFileSync('src/data/screens.json','utf8'));assert.equal(routes.length,86);for(const route of routes){h.events['design:route']({detail:{id:route.id}});assert.equal(h.root.dataset.designSample,'true',route.id);assert.equal(h.root.dataset.designRoute,route.id);}});
test('product appearance controls share ephemeral presentation without a storage API',()=>{const h=harness('?design=v4');h.preference('dark');assert.equal(h.root.dataset.designTheme,'dark');assert.equal(h.elements.designTheme.value,'dark');h.preference('opaque');assert.equal(h.root.dataset.designOpaque,'true');assert.equal(h.elements.designOpaque.checked,true);h.preference('opaque');assert.equal(h.root.dataset.designOpaque,'false');h.change('designVersion','baseline');h.preference('light');assert.equal(h.root.dataset.designTheme,'dark');});
