'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const M = require('../src/js/model.cjs');
const catalog = JSON.parse(fs.readFileSync(path.join(__dirname,'../src/data/screens.json'),'utf8'));
test('initial state is local only',()=>assert.equal(M.initial().remoteState,'disconnected'));
test('default has no implied camera consent',()=>assert.equal(M.initial().consent.camera,false));
test('independent initial objects',()=>{const a=M.initial(),b=M.initial();a.memories[0].text='x';assert.notEqual(b.memories[0].text,'x');});
test('schema validation rejects missing schema',()=>assert.throws(()=>M.validate({})));
test('schema validation rejects future schema',()=>assert.throws(()=>M.validate({schema:99})));
test('roundtrip has correct schema',()=>assert.equal(M.validate(M.initial()).schema,M.SCHEMA));
test('remote connection cannot be forged by backup',()=>assert.equal(M.validate({...M.initial(),remoteState:'connected'}).remoteState,'disconnected'));
test('restoring never resumes music or call state',()=>{const d=M.validate({...M.initial(),musicPlaying:true,callState:'active'});assert.equal(d.musicPlaying,false);assert.equal(d.callState,'idle');});
test('bounds volume',()=>{assert.equal(M.validate({...M.initial(),settings:{volume:999}}).settings.volume,100);assert.equal(M.validate({...M.initial(),settings:{volume:-2}}).settings.volume,0);});
test('nonfinite volume uses safe default',()=>assert.equal(M.validate({...M.initial(),settings:{volume:NaN}}).settings.volume,45));
test('nickname max length',()=>assert.equal(M.validate({...M.initial(),nickname:'a'.repeat(100)}).nickname.length,32));
test('strict consent booleans',()=>assert.equal(M.validate({...M.initial(),consent:{camera:'yes'}}).consent.camera,false));
test('messages bounded to 80',()=>assert.equal(M.validate({...M.initial(),messages:Array(100).fill({text:'t'})}).messages.length,80));
test('invalid list rejected',()=>assert.throws(()=>M.validate({...M.initial(),calendar:'not-list'})));
test('schedule restoration remains disabled',()=>{const d=M.validate({...M.initial(),schedules:[{id:'a',time:'10:30',enabled:true}]});assert.equal(d.schedules[0].enabled,false);});
test('invalid clock normalized',()=>{const d=M.validate({...M.initial(),schedules:[{time:'99:99'}],alarms:[{time:'25:00'}]});assert.equal(d.schedules[0].time,'09:00');assert.equal(d.alarms[0].time,'07:30');});
test('valid clock retained',()=>assert.equal(M.validate({...M.initial(),schedules:[{time:'23:59'}]}).schedules[0].time,'23:59'));
test('restore outbox cannot forge sent status',()=>assert.equal(M.validate({...M.initial(),localOutbox:[{text:'x',status:'sent'}]}).localOutbox[0].status,'local-preview-only'));
test('unknown fields dropped',()=>assert.equal(M.validate({...M.initial(),apiKey:'never-save'}).apiKey,undefined));
test('form drafts survive',()=>assert.equal(M.validate({...M.initial(),forms:{'DAY-02':{eventTitle:'会议'}}}).forms['DAY-02'].eventTitle,'会议'));
test('invalid form keys dropped',()=>assert.deepEqual(M.validate({...M.initial(),forms:{bad:{eventTitle:'x'}}}).forms,{}));
test('extract does not hallucinate extra lines',()=>assert.deepEqual(M.extractChecklist(' first \n\nsecond').map(x=>x.text),['first','second']));
test('empty notes extract empty checklist',()=>assert.deepEqual(M.extractChecklist(' \n '),[]));
test('checklist bounded',()=>assert.equal(M.extractChecklist(Array(250).fill('x').join('\n')).length,200));
test('square center crop geometry',()=>assert.deepEqual(M.centerCrop(900,600,'1:1'),{x:150,y:0,width:600,height:600}));
test('landscape crop remains in source',()=>{const r=M.centerCrop(600,900,'16:9');assert.equal(r.width,600);assert.ok(r.height<900&&r.y>0);});
test('invalid crop ratio rejected',()=>assert.throws(()=>M.centerCrop(900,600,'bad')));
test('invalid source geometry rejected',()=>{assert.throws(()=>M.centerCrop(0,600,'1:1'));assert.throws(()=>M.centerCrop(Infinity,600,'1:1'));});
test('empty search has no matches',()=>assert.deepEqual(M.search(catalog,'hello',' '),[]));
test('local notes searched with source label',()=>assert.equal(M.search(catalog,'hello world','hello')[0].type,'note'));
test('catalog search case insensitive',()=>assert.ok(M.search(catalog,'','img-02').some(x=>x.id==='IMG-02')));
test('approval payload detached and immutable',()=>{const raw={nested:{text:'first'}};const s=M.approvalSnapshot('message',raw);raw.nested.text='later';assert.equal(s.payload.nested.text,'first');assert.ok(Object.isFrozen(s.payload.nested));assert.throws(()=>{s.payload.nested.text='mutate';});});
