'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {create,CORE_KEY:C,SUITE_KEY:S,SNAPSHOT_KEY:K}=require('../src/js/storage.cjs');
function fixture(){
 const values=new Map([[C,'old core'],[S,'old suite']]),writes=[],removed=[];
 const raw={getItem:k=>values.has(k)?values.get(k):null,setItem(k,v){writes.push(k);if(raw.fail)throw Error('QuotaExceededError');values.set(k,v);},removeItem(k){removed.push(k);if(raw.failCleanup)throw Error('SecurityError');values.delete(k);}};
 return {values,writes,removed,raw,api:create(()=>raw)};
}
test('storage: legacy reads do not migrate or mutate',()=>{const f=fixture();assert.equal(f.api.getItem(C),'old core');assert.equal(f.api.getItem(S),'old suite');assert.equal(f.writes.length,0);});
test('storage: pre-restore edits retain the legacy format',()=>{const f=fixture();f.api.setItem(C,'edited');assert.equal(f.values.get(C),'edited');assert.equal(f.values.get(S),'old suite');assert.equal(f.values.has(K),false);});
test('storage: restore commits both namespaces in one write',()=>{const f=fixture();f.api.replace('new core','new suite');assert.deepEqual(f.writes,[K]);assert.equal(f.api.getItem(C),'new core');assert.equal(f.api.getItem(S),'new suite');});
test('storage: failed first restore preserves both legacy values',()=>{const f=fixture();f.raw.fail=true;assert.throws(()=>f.api.replace('new core','new suite'));assert.equal(f.values.get(C),'old core');assert.equal(f.values.get(S),'old suite');assert.equal(f.values.has(K),false);assert.equal(f.removed.length,0);});
test('storage: failed replacement preserves the complete committed pair',()=>{const f=fixture();f.api.replace('first core','first suite');const before=f.values.get(K);f.raw.fail=true;assert.throws(()=>f.api.replace('second core','second suite'));assert.equal(f.values.get(K),before);assert.equal(f.api.getItem(C),'first core');assert.equal(f.api.getItem(S),'first suite');});
test('storage: reload reads both values after commit',()=>{const f=fixture();f.api.replace('new core','new suite');const reloaded=create(()=>f.raw);assert.equal(reloaded.getItem(C),'new core');assert.equal(reloaded.getItem(S),'new suite');});
test('storage: cleanup interruption cannot expose a mixed pair',()=>{const f=fixture();f.raw.failCleanup=true;f.api.replace('new core','new suite');assert.equal(f.values.get(C),'old core');assert.equal(f.values.get(S),'old suite');const reloaded=create(f.raw);assert.equal(reloaded.getItem(C),'new core');assert.equal(reloaded.getItem(S),'new suite');});
test('storage: legacy data is removed only after successful commit',()=>{const f=fixture();f.api.replace('new core','new suite');assert.equal(f.values.has(C),false);assert.equal(f.values.has(S),false);assert.deepEqual(f.removed,[C,S]);});
test('storage: post-restore core save preserves suite',()=>{const f=fixture();f.api.replace('new core','new suite');f.api.setItem(C,'edited core');assert.equal(f.api.getItem(C),'edited core');assert.equal(f.api.getItem(S),'new suite');assert.equal(f.values.has(C),false);});
test('storage: post-restore suite save preserves core',()=>{const f=fixture();f.api.replace('new core','new suite');f.api.setItem(S,'edited suite');assert.equal(f.api.getItem(C),'new core');assert.equal(f.api.getItem(S),'edited suite');});
test('storage: failed post-restore edit preserves both stored values',()=>{const f=fixture();f.api.replace('core','suite');f.raw.fail=true;assert.throws(()=>f.api.setItem(C,'other'));assert.equal(f.api.getItem(C),'core');assert.equal(f.api.getItem(S),'suite');});
test('storage: each writer reads the latest committed counterpart',()=>{const f=fixture(),other=create(f.raw);f.api.replace('core','suite');other.setItem(S,'updated suite');f.api.setItem(C,'updated core');assert.equal(other.getItem(S),'updated suite');assert.equal(other.getItem(C),'updated core');});
test('storage: corrupt snapshot never falls back to mixed legacy state',()=>{const f=fixture();f.values.set(K,'{broken');assert.throws(()=>f.api.getItem(C));assert.throws(()=>f.api.getItem(S));assert.throws(()=>f.api.setItem(C,'new'));assert.equal(f.values.get(K),'{broken');});
test('storage: invalid snapshot version is preserved and rejected',()=>{const f=fixture();const bad=JSON.stringify({format:'ai-phone-ui-local-state',version:2,core:'c',suite:'s'});f.values.set(K,bad);assert.throws(()=>f.api.getItem(C));assert.throws(()=>f.api.setItem(S,'new'));assert.equal(f.values.get(K),bad);});
test('storage: inaccessible storage is reported before mutation',()=>{const api=create(()=>{throw Error('SecurityError');});assert.throws(()=>api.getItem(C));assert.throws(()=>api.setItem(C,'x'));assert.throws(()=>api.replace('c','s'));});
test('storage: nonserialized inputs cannot partially commit',()=>{const f=fixture();assert.throws(()=>f.api.replace({},'s'));assert.throws(()=>f.api.replace('c',null));assert.throws(()=>f.api.setItem(C,{}));assert.equal(f.writes.length,0);});
test('storage: unrelated keys cannot be read or mutated through adapter',()=>{const f=fixture();assert.throws(()=>f.api.getItem('unrelated'));assert.throws(()=>f.api.setItem('unrelated','x'));assert.equal(f.writes.length,0);});
