
'use strict';
// Gesture-first shell. Models and Android services are deliberately not simulated as real connections.
const $=id=>document.getElementById(id),W=360,H=672;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg aria-hidden="true"><use href="#i-${n}"/></svg>`;
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const NAMES={photo:'这张照片',notes:'我的想法',cloud:'资料整理',focus:'专注一刻'};
const STORE='ai-phone-ui-core-v1';
const DEFAULT_NOTE='手机，不该只是应用的入口。\n\n我希望它像 N9 一样，由边缘手势驱动。\n把内容轻轻推开，就看见还在运行的事情。\n\n手势负责指代与控制。\nAI 负责理解目的，服务负责可靠执行。\n\n前期先给每个人一个云端个人环境。\n回来时，从原来的地方继续。';
function defaults(){return {schema:3,theme:'sea',sound:false,reduce:false,notes:DEFAULT_NOTE,photo:{source:'',name:'山径 · 黄昏',current:2,selection:null,versions:[{id:'original',label:'原始画面',ops:[]},{id:'warm',label:'暖调',ops:[{type:'warm',region:null}]},{id:'cool',label:'冷调',ops:[{type:'cool',region:null}]}]},job:{status:'idle',progress:0,source:'',cursor:0,lines:[],items:[],result:''},focus:{seconds:900,running:false},messages:{photo:[],notes:[],cloud:[],focus:[]},drafts:{photo:'',notes:'',cloud:'',focus:''},events:[{title:'从一段连续的交互开始',body:'示例照片和笔记已经就位。没有连接云端服务。',task:'photo',at:Date.now()}]};}
function validate(o){if(!o||o.schema!==3||typeof o.notes!=='string'||o.notes.length>30000)throw Error('资料格式无效');const p=o.photo;if(!p||!Array.isArray(p.versions)||!p.versions.length||p.versions.length>24)throw Error('照片记录无效');if(p.source&&!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(p.source))throw Error('不允许外部图片地址');for(const v of p.versions){if(typeof v.id!=='string'||typeof v.label!=='string'||!Array.isArray(v.ops)||v.ops.length>24)throw Error('版本无效');for(const op of v.ops){if(!['warm','cool','bright','dark','vivid','mono','contrast','soft'].includes(op.type))throw Error('编辑类型无效');if(op.region&&!['x','y','r'].every(k=>Number.isFinite(op.region[k])&&op.region[k]>=0&&op.region[k]<=1))throw Error('选区无效');}}if(p.versions[0].ops.length)throw Error('缺少原图');p.current=clamp(Number.isInteger(p.current)?p.current:0,0,p.versions.length-1);p.selection=null;const d=defaults();const s={...d,...o};s.theme=['sea','dusk','rose'].includes(s.theme)?s.theme:'sea';s.messages={...d.messages,...s.messages};s.drafts={...d.drafts,...s.drafts};for(const k of Object.keys(NAMES)){s.messages[k]=Array.isArray(s.messages[k])?s.messages[k].slice(-30).map(m=>({role:m.role==='user'?'user':'assistant',text:String(m.text||'').slice(0,5000)})):[];s.drafts[k]=String(s.drafts[k]||'').slice(0,3000);}s.events=Array.isArray(s.events)?s.events.slice(0,25).map(e=>({title:String(e.title).slice(0,160),body:String(e.body).slice(0,500),task:NAMES[e.task]?e.task:'notes',at:Number(e.at)||Date.now()})):d.events;if(!s.job||!['idle','running','paused','done'].includes(s.job.status)||!Array.isArray(s.job.lines)||!Array.isArray(s.job.items)||typeof s.job.source!=='string'||typeof s.job.result!=='string')s.job=d.job;s.job.cursor=clamp(Number(s.job.cursor)||0,0,500);s.job.progress=clamp(Number(s.job.progress)||0,0,100);s.job.lines=s.job.lines.slice(0,200).map(x=>String(x).slice(0,3000));s.job.items=s.job.items.slice(0,200).map(x=>String(x).slice(0,3000));s.focus={seconds:clamp(Number.isFinite(s.focus?.seconds)?s.focus.seconds:900,0,900),running:false};return s;}
let S=defaults(),storageIssue=false;try{const v=PhoneStorage.getItem(STORE);if(v)S=validate(JSON.parse(v));}catch(e){storageIssue=true;}
if(S.job.status==='running')S.job.status='paused';
let scale=1,currentTask='photo',appOpen=false,homeIndex=1,stack=[],sessions={},overlay='',locked=false,sleeping=false,pulleyPinned=false,gesture=null,saveTimer=null,clickBlock=0,toastTimer=null,baseCanvas=null,imageCache=new Map(),voice=null,importSerial=0,ready=false;
let learned=new Set(),demoToken=0,demoRunning=false,lastTick=performance.now(),jobClock=0,focusSaveClock=0;
const activePointers=new Set();
// Each import review owns a shared candidate holder across shallow session copies.
// Clearing its value releases the file/snapshot and revokes every alias.
// Focus belongs to a particular review, never to a global last opener.
let focusedConfirmation=null,photoPickerOrigin=null;
function confirmationReturn(el=document.activeElement){return {task:currentTask,id:el?.id||'',action:el?.dataset.action||'',menu:el?.dataset.menu??null,pulley:!!el?.closest('#pulley')};}
function activeConfirmation(){
  const el=topPage();
  return appOpen&&!overlay&&!locked&&!sleeping&&stack.at(-1)?.kind==='confirm'&&
    el&&!el.closest('[inert]')&&!$('helpOverlay').classList.contains('open')?el:null;
}
function syncConfirmationFocus(){
  const el=activeConfirmation();
  if(el!==focusedConfirmation){el?.querySelector('[data-action="back"]')?.focus({preventScroll:true});focusedConfirmation=el?.contains(document.activeElement)?el:null;}
}
function confirmationKey(e){
  const el=activeConfirmation();
  if(!el||e.ctrlKey||e.metaKey||e.altKey)return false;
  if(e.key==='Escape'){e.preventDefault();backPage();return true;}
  if(el.contains(document.activeElement)&&['ArrowDown','ArrowUp','PageDown','PageUp','Home','End'].includes(e.key)){
    const body=el.querySelector('.dialog-inner');
    if(body&&body.scrollHeight>body.clientHeight){
      e.preventDefault();
      const step=e.key.startsWith('Page')?body.clientHeight*.9:40;
      body.scrollTop=e.key==='Home'?0:e.key==='End'?body.scrollHeight:body.scrollTop+(['ArrowUp','PageUp'].includes(e.key)?-step:step);
      return true;
    }
  }
  if(e.key!=='Tab')return false;
  const first=el.querySelector('[data-action="back"]'),last=el.querySelector('[data-action="accept"]');
  if(document.activeElement!==first&&document.activeElement!==last||e.shiftKey&&document.activeElement===first||!e.shiftKey&&document.activeElement===last){
    e.preventDefault();(e.shiftKey?last:first)?.focus({preventScroll:true});
  }
  return true;
}
function restoreConfirmationFocus(page,cancelled=true){
  if(page?.kind!=='confirm'||!appOpen||overlay||locked||sleeping)return;
  const origin=page.returnFocus;
  if(cancelled&&page.mode==='import'&&origin?.task!==currentTask&&NAMES[origin?.task])openTask(origin.task,{noAnimation:true});
  const review=activeConfirmation();
  if(review){review.querySelector('[data-action="back"]')?.focus({preventScroll:true});return;}
  if(origin?.task===currentTask){
    if(cancelled&&origin.pulley&&!stack.length)pinPulley();
    const root=cancelled&&origin.pulley&&pulleyPinned?$('pulley'):topPage()||$('taskSurface');
    const target=[...root.querySelectorAll('[data-action], [id]')].find(el=>
      (origin.id?el.id===origin.id:origin.action&&el.dataset.action===origin.action&&
        (origin.menu===null||el.dataset.menu===origin.menu))&&!el.closest('[inert]')&&el.getClientRects().length);
    if(target){target.focus({preventScroll:true});return;}
  }
  // A gesture/deep-link may have no button opener; keep a visible task anchor.
  const root=topPage()||$('taskSurface');root.tabIndex=-1;root.focus({preventScroll:true});
}
function choosePhoto(inputId){
  photoPickerOrigin={focus:confirmationReturn(),task:currentTask,page:stack.at(-1),appOpen};
  $(inputId).click();
}
function saveNow(){clearTimeout(saveTimer);try{PhoneStorage.setItem(STORE,JSON.stringify(S));$('storageError').hidden=true;}catch{$('storageError').hidden=false;}}
function save(){clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,220);}
function addEvent(title,body,task=currentTask){S.events.unshift({title,body,task,at:Date.now()});S.events=S.events.slice(0,25);renderEvents();save();}
function toast(text,ms=2300){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),ms);}
function report(title,text,mark){$('monitorTitle').textContent=title;$('monitorText').textContent=text;if(mark)learned.add(mark);['open','peek','home','cover','pulley'].forEach((m,i)=>$('trainingProgress').children[i].classList.toggle('done',learned.has(m)));}
function hint(text){$('gestureToast').textContent=text;$('gestureToast').classList.toggle('show',!!text);}
function feedback(){try{navigator.vibrate?.(9);}catch{}if(!S.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;feedback.ctx??=new C();const ctx=feedback.ctx;ctx.resume();const o=ctx.createOscillator(),v=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(790,ctx.currentTime);v.gain.setValueAtTime(.028,ctx.currentTime);v.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.035);o.connect(v);v.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.04);}catch{}}
const viewportTransforms=new WeakMap();
function viewportSize(){const el=$('screen');return {width:el?.clientWidth||W,height:el?.clientHeight||H};}
function viewX(value){return value*viewportSize().width/W;}
function viewY(value){return value*viewportSize().height/H;}
function viewportTransform(value){return value.replace(/translate([XY])\((-?[\d.]+)px\)/g,(_,axis,n)=>`translate${axis}(${axis==='X'?viewX(Number(n)):viewY(Number(n))}px)`).replace(/translate3d\((-?[\d.]+)px,0,0\)/g,(_,n)=>`translate3d(${viewX(Number(n))}px,0,0)`);}
function viewportStyles(el,values){if(typeof values.transform!=='string')return values;viewportTransforms.set(el,values.transform);return {...values,transform:viewportTransform(values.transform)};}
function refreshViewportTransforms(){for(const el of $('screen').querySelectorAll('[style]')){const value=viewportTransforms.get(el);if(value!==undefined){el.style.transition='none';el.style.transform=viewportTransform(value);}}}
function animateStyle(el,values,duration=270){el.style.transition=S.reduce?'none':`transform ${duration}ms cubic-bezier(.18,.76,.22,1), opacity ${duration}ms`;Object.assign(el.style,viewportStyles(el,values));}
function direct(el,values){el.style.transition='none';Object.assign(el.style,viewportStyles(el,values));}
function fit(){const r=$('deviceArea').getBoundingClientRect();if(!r.width||!r.height)return;const width=$('phone').offsetWidth||390,height=$('phone').offsetHeight||756,size=viewportSize(),key=size.width+'x'+size.height,layoutKey=[r.left,r.top,r.width,r.height].join(':'),nextScale=Math.max(.25,Math.min((r.width-8)/width,(r.height-4)/height,1.04));if(fit.viewportKey&&gesture&&(fit.viewportKey!==key||fit.layoutKey!==layoutKey||Math.abs(nextScale-scale)>1e-6)){finishGesture(null,true);activePointers.clear();}scale=nextScale;document.documentElement.style.setProperty('--scale',scale);$('deviceSlot').style.width=width*scale+'px';$('deviceSlot').style.height=height*scale+'px';if(fit.viewportKey!==key){refreshViewportTransforms();fit.viewportKey=key;}fit.layoutKey=layoutKey;renderPhotoSelection();}
window.addEventListener('resize',fit);window.visualViewport?.addEventListener('resize',fit);
function clock(){const d=new Date(),t=d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});$('clock').textContent=$('lockTime').textContent=t;$('lockDate').textContent=d.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});}
function theme(){const t={sea:['#a2e8e0','#245460','hue-rotate(68deg) saturate(.68) brightness(.72)','#087e9d'],dusk:['#ffcfb1','#694943','hue-rotate(295deg) saturate(.70) brightness(.70)','#aa685f'],rose:['#e2bef2','#51465f','hue-rotate(175deg) saturate(.55) brightness(.63)','#635277']}[S.theme];['--accent','--tone','--wall-filter','--device'].forEach((v,i)=>document.documentElement.style.setProperty(v,t[i]));document.body.classList.toggle('reduce-motion',S.reduce);document.querySelectorAll('.ambience').forEach(el=>el.classList.toggle('on',el.dataset.action==='theme-'+S.theme));$('soundState').textContent=S.sound?'已开启':'关闭';$('motionState').textContent=S.reduce?'已开启':'关闭';}
function syncAccess(){const systemBlocked=appOpen||!!overlay||locked||sleeping;$('system').inert=systemBlocked;$('task').inert=!appOpen||!!overlay||locked||sleeping;$('taskSurface').inert=stack.length>0;$('stackRoot').querySelectorAll('.stack-page').forEach((p,i)=>p.inert=i!==stack.length-1);$('topMenu').inert=overlay!=='top';$('launcher').inert=overlay!=='caps';$('lock').inert=!locked||sleeping;$('sleep').inert=!sleeping;['eventsPage','homePage','capsPage'].forEach((id,i)=>$(id).inert=i!==homeIndex||systemBlocked);syncConfirmationFocus();}
function setHome(index,animate=true){homeIndex=clamp(index,0,2);(animate?animateStyle:direct)($('systemTrack'),{transform:`translateX(${-homeIndex*W}px)`});[...$('systemDots').children].forEach((el,i)=>el.classList.toggle('on',i===homeIndex));syncAccess();}
function captureSession(){if(photoPickerOrigin)photoPickerOrigin.abandoned=true;if(!appOpen)return;const input=$('talkInput');if(input)S.drafts[currentTask]=input.value;const scrollEl=$('stackRoot').lastElementChild?.querySelector('.stack-scroll,.talk-history');sessions[currentTask]={stack:stack.map(x=>({...x})),scroll:scrollEl?.scrollTop||0,noteScroll:$('noteEditor')?.scrollTop||0};}
function openTask(id,options={}){if(!NAMES[id])return;if(!ready){toast('图片还在准备中');return;}if(overlay)closeOverlay(true);if(locked||sleeping){locked=sleeping=false;$('lock').classList.remove('visible');$('sleep').classList.remove('visible');}const same=currentTask===id;captureSession();currentTask=id;options.prepareView?.();if(!same){stack=sessions[id]?.stack?.map(x=>({...x}))||[];renderRoot();renderStack();}else if(!$('surfaceContent').children.length){renderRoot();renderStack();}appOpen=true;pulleyPinned=false;setHome(1,false);$('task').classList.add('open');direct($('task'),{transform:'translate3d(0,0,0)',opacity:'1'});direct($('taskSurface'),{transform:'translateY(0)'});$('pulley').classList.remove('visible');syncAccess();if(!S.reduce&&!options.noAnimation){const r=document.querySelector(`[data-task="${id}"]`).getBoundingClientRect(),s=$('screen').getBoundingClientRect();const l=(r.left-s.left)/scale,t=(r.top-s.top)/scale,rr=viewportSize().width-l-r.width/scale,bb=viewportSize().height-t-r.height/scale;const animation=$('task').animate([{clipPath:`inset(${t}px ${rr}px ${bb}px ${l}px)`},{clipPath:'inset(0px 0px 0px 0px)'}],{duration:290,easing:'cubic-bezier(.18,.76,.22,1)'});animation.finished.catch(()=>{});}if(!same){const sess=sessions[id];if(sess){const e=$('stackRoot').lastElementChild?.querySelector('.stack-scroll,.talk-history');if(e)e.scrollTop=sess.scroll;if($('noteEditor'))$('noteEditor').scrollTop=sess.noteScroll;}}report('内容在前，任务在后','从屏幕左 / 右边缘推开；画面内部的滑动不负责返回主屏。','open');feedback();}
function minimize(animate=true){if(!appOpen)return;captureSession();stopVoice();pulleyPinned=false;$('pulley').classList.remove('visible');direct($('taskSurface'),{transform:'translateY(0)'});const task=$('task');appOpen=false;setHome(1,false);if(animate){const token=uid();minimize.token=token;animateStyle(task,{transform:`translateX(${W}px)`},230);setTimeout(()=>{if(!appOpen&&minimize.token===token){task.classList.remove('open');direct(task,{transform:'translateX(0)'});}},235);}else{task.classList.remove('open');direct(task,{transform:'translateX(0)'});}syncAccess();report('推开内容 → 活动任务','当前任务只是最小化。正在运行的整理与计时不会因此暂停。','home');}
function topPage(){return $('stackRoot').lastElementChild;}
function resetPulley(animate=true){pulleyPinned=false;(animate?animateStyle:direct)($('taskSurface'),{transform:'translateY(0)'});$('pulley').classList.remove('visible');}
function menuItems(){switch(currentTask){case'photo':return [{label:'暖一点',action:'warm',sub:'本机像素处理'},{label:'版本与原图',action:'history',sub:'查看编辑记录'},{label:'收好这一版',action:'export-photo',sub:'PNG 导出'}];case'notes':return [{label:'记下新的想法',action:'talk',sub:'继续这段上下文'},{label:'交给整理任务',action:'job-from-note',sub:'在本页分步运行'},{label:'导出这份笔记',action:'export-note',sub:'纯文本'}];case'cloud':return [{label:S.job.status==='running'?'暂停整理':S.job.status==='done'?'重新整理':'开始 / 继续',action:'job-toggle',sub:'保留执行状态'},{label:'查看整理结果',action:'job-result',sub:'来自笔记原文'},{label:'继续交代',action:'talk',sub:'当前任务上下文'}];case'focus':return [{label:S.focus.running?'暂停专注':'开始 / 继续',action:'focus-toggle',sub:'十五分钟'},{label:'重新计时',action:'focus-reset',sub:'恢复 15:00'},{label:'继续交代',action:'talk',sub:'当前任务上下文'}];}}
function renderPulley(){const items=menuItems();$('pulley').innerHTML=items.map((v,i)=>`<button class="pulley-row" data-action="pulley-action" data-menu="${i}"><small>0${i+1}</small>${v.label}</button>`).join('')+'<div class="pulley-hint">松手执行 · 往回推取消</div>';}
function pulleyPreview(d){$('pulley').classList.add('visible');const amount=Math.max(0,Math.min(d,295));direct($('taskSurface'),{transform:`translateY(${amount}px)`});const i=d>=68?clamp(Math.floor((d-68)/56),0,2):-1;const pinned=d>=258;[...$('pulley').querySelectorAll('.pulley-row')].forEach((e,k)=>e.classList.toggle('selected',!pinned&&k===i));if(gesture&&gesture.selected!==i){if(i>=0)feedback();gesture.selected=i;}hint(pinned?'松手固定菜单，也可以点选':i<0?'向下拉出菜单，往回推可取消':'松手：'+menuItems()[i].label);report('内容内部下拉 → 拉绳菜单',pinned?'深拉固定菜单；没有自动提交操作。':i<0?'继续往下；指令由拉动距离决定。':`选中「${menuItems()[i].label}」，现在推回去仍能取消。`);return {i,pinned};}
function pinPulley(){if(!appOpen||stack.length)return;renderPulley();pulleyPinned=true;$('pulley').classList.add('visible');animateStyle($('taskSurface'),{transform:'translateY(230px)'});report('Pulley 已展开','点选一个命令，或把内容往上推回。');}
function header(title,eyebrow,meta=''){return `<div class="page-dots"><span class="on"></span><span></span></div><div class="app-header"><div class="eyebrow">${eyebrow}</div><h2>${title}</h2><div class="metadata">${meta}</div></div>`;}
function renderRoot(){let html='';if(currentTask==='photo'){html=header(esc(S.photo.name),'LOOK / CREATE','下拉有菜单 · 右侧亮点之后是版本记录')+'<div class="attached-dot"></div><div class="photo-stage" id="photoStage"><canvas id="photoCanvas"></canvas><div class="selection" id="selection" hidden></div></div><div class="photo-meta"><strong id="photoLabel"></strong><small id="photoVersion"></small></div><div class="task-hint" id="photoHint">内部横滑比较版本 · 长按继续交代</div>';}else if(currentTask==='notes'){html=header('别让想法走丢','MEMORY / CONTINUE','下拉交给整理任务 · 文字自动保存在本机')+'<textarea id="noteEditor" class="notes-editor" maxlength="30000" spellcheck="false" aria-label="编辑你的笔记"></textarea><div class="note-counter" id="noteCount"></div>';}else if(currentTask==='cloud'){html=header('把想法整理好','PERSONAL RUNTIME / 本机演示','前台离开，当前网页里的执行可以继续。')+'<div class="job-detail"><div class="big-percent"><span id="jobPercent">0</span><small>%</small></div><div class="meter"><i id="jobMeter"></i></div><p class="job-desc" id="jobDesc"></p><div class="job-phases" id="jobPhases"><span>读取这一次的原文快照</span><span>逐条提取并去掉重复行</span><span>组装可下载的文字成果</span></div><p class="job-foot">没有连接云端，没有 AI 改写。<br>关闭网页不会后台执行；重新打开等待你继续。</p></div><div class="task-hint">下拉：运行 / 暂停 · 结果 · 继续交代</div>';}else{html=header('给自己一刻','FOCUS / 15 MINUTES','最小化后，在活动封面上继续控制。')+'<div class="focus-body"><div class="focus-circle"><div class="focus-timer" id="focusTime">15:00</div></div><p id="focusDesc">下拉开始。<br>给眼前这件事十五分钟。</p></div><div class="task-hint">下拉：运行 / 暂停 · 重新计时</div>';}$('surfaceContent').innerHTML=html;renderPulley();if(currentTask==='photo')renderPhoto();if(currentTask==='notes'){const e=$('noteEditor');e.value=S.notes;noteCount();}renderJob();renderFocus();}
function childFrame(kind,content,headerHTML){return `<div class="stack-page" data-kind="${kind}">${headerHTML}${content}</div>`;}
function renderStack(){const box=$('stackRoot');box.innerHTML='';stack.forEach((page,i)=>{const title=page.kind==='history'?'留下来的版本':page.kind==='talk'?'接着说。':page.kind==='result'?'整理结果':'';let head=header(esc(title),page.kind==='talk'?`WITH CONTEXT / ${NAMES[currentTask]}`:'CONTINUITY / PAGE '+(i+2),'内部右滑回上一层 · 边缘滑动回活动任务');let content='';if(page.kind==='history'){content='<div class="stack-scroll">'+S.photo.versions.map((v,idx)=>`<button class="history-row ${idx===S.photo.current?'selected':''}" data-action="select-version" data-index="${idx}"><span>${esc(v.label)}<small>${idx===0?'原图从未覆盖':v.ops.length+' 次本机编辑'}</small></span><span>${idx===S.photo.current?'✓':'0'+(idx+1)}</span></button>`).join('')+'</div>';}else if(page.kind==='talk'){content='<div class="talk-history" id="talkHistory"></div><div class="talk-input"><textarea id="talkInput" maxlength="3000" aria-label="继续交代你的要求" placeholder="试试：暖一点 / 记下：新的想法"></textarea><div class="talk-actions"><button data-action="voice">'+icon('mic')+'语音（需授权）</button><button class="send" data-action="send">发送'+icon('arrow')+'</button></div></div>';head=header(title,'WITH CONTEXT / '+NAMES[currentTask],'本机规则演示 · 未连接大模型');}else if(page.kind==='result'){content='<div class="stack-scroll">'+esc(S.job.result||'整理尚未完成。返回活动封面，向右滑开始或继续。')+'</div><div class="task-hint"><button data-action="export-result">'+(S.job.result?'导出结果 →':'')+'</button></div>';}else if(page.kind==='confirm'){head='<div class="dialog-head"><button data-action="back">← 取消</button><button class="accept" data-action="accept">'+(page.mode==='import'?'替换导入':page.mode==='voice'?'授权继续':page.mode==='suite'&&page.suiteMode==='restore'?'确认恢复':page.mode==='suite'&&page.suiteMode==='message'?'确认本机预览':'确认导出')+' <i></i></button></div>';content='<div class="dialog-inner stack-scroll"><h2>'+esc(page.title)+'</h2>'+(page.mode==='photo'?'<canvas class="dialog-preview" id="exportPreview"></canvas>':'')+'<p>'+esc(page.description)+'</p></div><div class="dialog-hint"><span>右滑取消 →</span><span>← 左滑接受</span></div>';}
box.insertAdjacentHTML('beforeend',childFrame(page.kind,content,head));});if(stack.length){const p=stack.at(-1);if(p.kind==='talk'){renderTalk();$('talkInput').value=S.drafts[currentTask]||'';}if(p.kind==='confirm'&&p.mode==='photo'&&$('exportPreview')){const v=S.photo.versions.find(v=>v.id===p.versionId);if(v){const c=versionCanvas(v),out=$('exportPreview');out.width=c.width;out.height=c.height;out.getContext('2d').drawImage(c,0,0);}}}syncAccess();}
function pushPage(page,animate=true){if(page.kind==='confirm')page.returnFocus??=confirmationReturn();if(!appOpen)openTask(currentTask);if(stack.length>6)return;stopVoice();if($('talkInput'))S.drafts[currentTask]=$('talkInput').value;resetPulley(false);stack.push(page);renderStack();if(animate&&!S.reduce)topPage().animate([{transform:`translateX(${viewX(W)}px)`},{transform:'translateX(0)'}],{duration:265,easing:'cubic-bezier(.18,.76,.22,1)'});report('页面有深度，不再弹出底部面板','内容内部向右回到父页面；从屏幕边缘滑动仍会最小化整个任务。');}
function backPage(){stopVoice();if($('talkInput'))S.drafts[currentTask]=$('talkInput').value;if(stack.length){const page=stack.pop();if(page.candidate)page.candidate.value=null;renderStack();restoreConfirmationFocus(page);save();report('返回父页面','只退一层，不回到主屏，也不退出当前任务。');}else minimize();}
function talk(){if(!appOpen)openTask(currentTask);if(stack.at(-1)?.kind==='talk')return;pushPage({kind:'talk'});}
function exportConfirm(mode,returnFocus){if(!appOpen)openTask(mode==='photo'?'photo':mode==='notes'?'notes':'cloud');let page={kind:'confirm',mode,returnFocus,title:mode==='photo'?'收好这一版':'导出这份文字',description:'确认后交给浏览器下载，不会发送到外部服务。'};if(mode==='photo'){const v=S.photo.versions[S.photo.current];page.versionId=v.id;page.description='已固定：'+v.label+'\n只导出这个版本，原图不会被覆盖。\n\n向左滑接受；向右滑取消。';}else{page.text=mode==='notes'?S.notes:S.job.result;page.description+='\n已固定当前文字快照。\n\n向左滑接受；向右滑取消。';}pushPage(page);}
function downloadBlob(blob,name){if(!blob)return;const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),20000);}
function downloadText(text,name,type='text/plain;charset=utf-8'){downloadBlob(new Blob([text],{type}),name);}
function acceptDialog(){const p=stack.at(-1);if(!p||p.kind!=='confirm'||p.consumed||p.mode==='import'&&!p.candidate?.value)return;const candidate=p.candidate?.value;if(p.candidate)p.candidate.value=null;p.consumed=true;stack.pop();renderStack();restoreConfirmationFocus(p,false);if(p.mode==='photo'){const v=S.photo.versions.find(v=>v.id===p.versionId);if(!v){toast('版本已不存在，请重新选择');return;}versionCanvas(v).toBlob(blob=>{if(!blob){toast('导出失败');return;}downloadBlob(blob,'SWIPE-'+p.versionId+'.png');addEvent('图片已交给浏览器下载',v.label+'；原图未覆盖。','photo');toast('PNG 已交给浏览器下载');},'image/png');}else if(p.mode==='import'){importImage(candidate);}else if(p.mode==='voice'){startVoice();}else{downloadText(p.text||'',p.mode==='notes'?'我的想法.txt':'整理结果.md');addEvent('文字已交给浏览器下载','导出的是确认页打开时的快照。',p.mode==='notes'?'notes':'cloud');toast('文字已交给浏览器下载');}report('向左接受 → 提交固定内容','向右取消，反向拖回也能取消；不会导出后台刚变更的其他版本。');}
function renderTalk(){if(!$('talkHistory'))return;const arr=S.messages[currentTask];$('talkHistory').innerHTML=(arr.length?arr:[{role:'assistant',text:currentTask==='photo'?'这一句会作用在当前照片上。\n试试「暖一点」「黑白」「亮一点」；先点照片，可以只处理圆形选区。':'上下文还在这里。\n试试「记下：新的想法」「暂停整理」「继续整理」。'}]).map(m=>`<div class="utterance ${m.role==='user'?'user':''}"><small>${m.role==='user'?'你':'本机交互解释'}</small>${esc(m.text)}</div>`).join('');$('talkHistory').scrollTop=$('talkHistory').scrollHeight;}
function promptSend(text){const value=(text??$('talkInput')?.value??'').trim();if(!value)return;const key=currentTask;S.messages[key].push({role:'user',text:value});let answer='这个原型还没有连接大模型。当前支持照片调色、记下文字、整理笔记、暂停或继续任务；不会假装替你完成其他事情。';const t=value.toLowerCase();const mapping=[['黑白','mono'],['暖','warm'],['冷','cool'],['亮','bright'],['暗','dark'],['鲜明','vivid'],['柔和','soft'],['对比','contrast']];if(/^记下[:：\s]/.test(value)){const note=value.replace(/^记下[:：\s]+/,'');if(note){S.notes=(S.notes+'\n\n'+note).slice(0,30000);renderNoteCover();answer='已追加到你的笔记。可以在活动封面里看到，不需要重新打开应用。';}}else if(/(暂停|停止).*整理|整理.*(暂停|停止)/.test(t)){pauseJob();answer='整理已暂停，原文快照和进度保留。';}else if(/(继续|开始).*整理|整理.*(继续|开始)/.test(t)){startOrResumeJob();answer='整理已在当前网页里开始。最小化只是离开前台，任务继续执行。';}else if(key==='photo'&&/(取消选区|整张)/.test(t)){S.photo.selection=null;renderPhoto();answer='已取消圆形选区，下次修改整张图片。';}else if(key==='photo'&&mapping.find(([s])=>t.includes(s))){const op=mapping.find(([s])=>t.includes(s))[1];answer=applyEdit(op)?'已完成真实的本机像素调整，新增一个版本。原图保留；回到图片内部左右滑动比较。':'版本数量已到上限，请先导出。';}else if(key==='photo'&&/换背景|生图|移除|人物不变/.test(t)){answer='这一版没有接生成模型，不能真正换背景或保证人物重绘不变。现在可以做局部色调调整，且保留原图。';}S.messages[key].push({role:'assistant',text:answer});S.messages[key]=S.messages[key].slice(-30);S.drafts[key]='';if($('talkInput'))$('talkInput').value='';renderTalk();save();}
function stopVoice(){const r=voice;voice=null;if(r)try{r.abort();}catch{}}
function voiceEntry(){talk();if(!(window.SpeechRecognition||window.webkitSpeechRecognition)){toast('浏览器不支持语音识别，请直接输入文字');return;}pushPage({kind:'confirm',mode:'voice',title:'使用浏览器语音识别',description:'这会请求麦克风权限。浏览器可能将音频交给其在线识别服务。\n识别结果只填入文本框，由你确认后发送。\n\n向左滑同意；向右滑取消。'});}
function startVoice(){talk();const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return;stopVoice();const r=new R();voice=r;r.lang='zh-CN';r.interimResults=true;r.continuous=false;const taskId=currentTask;r.onresult=e=>{if(voice!==r)return;let text='';for(const res of e.results)text+=res[0].transcript;S.drafts[taskId]=text;if(currentTask===taskId&&$('talkInput'))$('talkInput').value=text;save();};r.onend=()=>{if(voice===r){voice=null;toast('收音结束，请检查文字再发送');}};r.onerror=e=>{if(voice===r){voice=null;toast('语音未完成：'+e.error);}};try{r.start();toast('正在收音；返回或最小化会停止');}catch{voice=null;toast('无法启动语音，请输入文字');}}
// Actual local image rendering; preserve source and derive immutable versions.
function versionCanvas(v){if(imageCache.has(v.id))return imageCache.get(v.id);const c=cloneCanvas(baseCanvas);v.ops.forEach(op=>applyPixels(c,op));imageCache.set(v.id,c);while(imageCache.size>4)imageCache.delete(imageCache.keys().next().value);return c;}
function photoViewport(c=baseCanvas){const stage=$('photoStage'),width=stage?.clientWidth||W,height=stage?.clientHeight||424,f=Math.min(width/c.width,height/c.height),imageWidth=c.width*f,imageHeight=c.height*f;return {width,height,imageWidth,imageHeight,left:(width-imageWidth)/2,top:(height-imageHeight)/2};}
function renderPhotoSelection(c=baseCanvas){const ring=$('selection');if(!ring||!c||!$('photoStage'))return;const sel=S.photo.selection;ring.hidden=!sel;if(!sel)return;const g=photoViewport(c),r=sel.r*Math.min(g.imageWidth,g.imageHeight);ring.style.cssText=`left:${g.left+sel.x*g.imageWidth-r}px;top:${g.top+sel.y*g.imageHeight-r}px;width:${r*2}px;height:${r*2}px;`;}
function renderPhoto(){if(!baseCanvas)return;const v=S.photo.versions[S.photo.current],c=versionCanvas(v);if($('photoCanvas')){const out=$('photoCanvas');out.width=c.width;out.height=c.height;out.getContext('2d').drawImage(c,0,0);$('photoLabel').textContent=v.label;$('photoVersion').textContent=`${S.photo.current+1} / ${S.photo.versions.length}`;const sel=S.photo.selection;renderPhotoSelection(c);$('photoHint').textContent=sel?'圆形局部已选中 · 下拉调色 · 长按继续交代':'内部横滑比较版本 · 长按继续交代';}const out=$('coverPhoto');out.width=180;out.height=215;const f=Math.max(180/c.width,215/c.height);out.getContext('2d').drawImage(c,(180-c.width*f)/2,(215-c.height*f)/2,c.width*f,c.height*f);$('coverPhotoLabel').textContent=v.label+' · 第 '+(S.photo.current+1)+' 个版本';}
function photoNext(delta){const i=clamp(S.photo.current+delta,0,S.photo.versions.length-1);if(i===S.photo.current){toast(delta<0?'已经是原图':'已经是最新版本');return;}S.photo.current=i;renderPhoto();save();feedback();}
function applyEdit(type){if(!baseCanvas||S.photo.versions.length>=24)return false;const cur=S.photo.versions[S.photo.current];const label={warm:'暖调',cool:'冷调',bright:'明亮',dark:'深调',mono:'黑白',vivid:'鲜明',soft:'柔和',contrast:'对比'}[type];if(!label)return false;const op={type,region:S.photo.selection?{...S.photo.selection}:null};const v={id:uid(),label:(op.region?'局部 · ':'')+label,ops:[...cur.ops,op]};S.photo.versions.push(v);S.photo.current=S.photo.versions.length-1;renderPhoto();save();feedback();return true;}
function selectPhoto(e){if(!baseCanvas||!$('photoStage'))return;const r=$('photoStage').getBoundingClientRect();if(!r.width||!r.height)return;const g=photoViewport(baseCanvas),x=(e.clientX-r.left)*g.width/r.width,y=(e.clientY-r.top)*g.height/r.height;if(x<g.left||x>g.left+g.imageWidth||y<g.top||y>g.top+g.imageHeight)return;S.photo.selection={x:(x-g.left)/g.imageWidth,y:(y-g.top)/g.imageHeight,r:.23,protect:false};renderPhoto();save();toast('已选中圆形区域；下拉或长按继续操作',1600);}
function fileChosen(file){const origin=photoPickerOrigin;photoPickerOrigin=null;if(!file)return;if(origin&&(origin.abandoned||origin.task!==currentTask||origin.page!==stack.at(-1)||origin.appOpen!==appOpen))return;const returnFocus=origin?.focus||confirmationReturn();if(!appOpen||currentTask!=='photo')openTask('photo');pushPage({kind:'confirm',mode:'import',candidate:{value:file},returnFocus,title:'用这张照片继续',description:'导入后替换当前照片工作区。原有图片版本将不再显示，请先导出需要的版本。\n\n新照片只在当前浏览器处理，不上传。'});}
async function importImage(file){const serial=++importSerial;try{const src=await decodeFile(file),img=new Image();await new Promise((yes,no)=>{img.onload=yes;img.onerror=()=>no(Error('图片无法读取'));img.src=src;});if(serial!==importSerial)return;const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);baseCanvas=c;S.photo={source:src,name:(file.name||'我的照片').slice(0,35),current:0,selection:null,versions:[{id:uid(),label:'原始画面',ops:[]}]};imageCache.clear();sessions.photo={stack:[]};if(currentTask==='photo'){stack=[];renderRoot();renderStack();}renderPhoto();addEvent('照片已导入',file.name+'；工作副本只保存在本机。','photo');saveNow();toast('照片已导入，没有上传');}catch(e){toast(e.message||'导入失败');}}
function renderNoteCover(){$('coverNotePreview').textContent=S.notes.replace(/\s+/g,' ').slice(0,75)||'还没有留下想法。';noteCount();}
function noteCount(){if($('noteCount'))$('noteCount').textContent=S.notes.length+' 字 · 自动保存在本机';}
function startOrResumeJob(){const j=S.job;if(j.status==='running')return;if(j.status==='idle'||j.status==='done'){const lines=S.notes.split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,200);if(!lines.length){toast('先在笔记里写点内容');return;}S.job={status:'running',progress:0,source:S.notes,cursor:0,lines,items:[],result:''};addEvent('开始整理原文快照','不是 AI 改写，按原文非空行提取并去重。','cloud');}else j.status='running';jobClock=0;renderJob();save();}
function pauseJob(){if(S.job.status==='running'){S.job.status='paused';renderJob();save();}}
function toggleJob(){if(S.job.status==='running')pauseJob();else startOrResumeJob();feedback();}
function jobStep(){const j=S.job;if(j.status!=='running')return;if(j.cursor<j.lines.length){const line=j.lines[j.cursor];if(!j.items.includes(line))j.items.push(line);j.cursor++;j.progress=Math.round(j.cursor/(j.lines.length+2)*100);}else if(j.cursor===j.lines.length){j.cursor++;j.progress=Math.round(j.cursor/(j.lines.length+2)*100);}else{j.result='# 我的想法 · 原文整理\n\n处理方式：按非空行提取，保留原文、去掉重复行；没有 AI 改写。\n\n'+j.items.map((line,i)=>`${i+1}. ${line}`).join('\n\n')+'\n\n---\n来源：开始整理时的笔记快照。\n';j.progress=100;j.status='done';addEvent('整理完成，回来就能接着看',j.items.length+' 条原文已整理；结果没有离开浏览器。','cloud');if(appOpen&&currentTask==='cloud'&&stack.at(-1)?.kind==='result')renderStack();toast('笔记整理完成 · 活动封面已更新');}renderJob();save();}
function renderJob(){const j=S.job;const labels={idle:'右滑封面 → 开始',running:'正在整理 · 右滑暂停',paused:'已暂停 · 右滑继续',done:'完成 · 左滑查看'};$('coverJobPercent').textContent=Math.round(j.progress);$('coverJobMeter').style.width=j.progress+'%';$('coverJobLabel').textContent=labels[j.status];$('coverJobIcon').innerHTML=`<use href="#i-${j.status==='running'?'pause':j.status==='done'?'check':'play'}"/>`;if($('jobPercent')){$('jobPercent').textContent=Math.round(j.progress);$('jobMeter').style.width=j.progress+'%';$('jobDesc').textContent={idle:'从画面内部下拉，开始整理当前笔记。',running:'正在处理开始时的原文快照。你可以推开本页，去看另一件事。',paused:'执行已暂停。下拉继续，或在活动封面上向右滑。',done:'整理完成。下拉选择「查看整理结果」。'}[j.status];[...$('jobPhases').children].forEach((el,i)=>el.classList.toggle('done',j.progress>=[1,65,100][i]));}if(appOpen&&currentTask==='cloud'&&!gesture&&!pulleyPinned)renderPulley();$('lockMessage').innerHTML=j.status==='running'?'原文整理正在本网页中继续。<br>锁屏没有停止这件事。':'你的事情仍在这里。<br>不是退出，只是暂时离开。';}
function renderEvents(){$('eventsList').innerHTML=S.events.map(e=>`<button class="event" data-action="event" data-target="${e.task}"><span class="go">→</span><time>${new Date(e.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}</time><strong>${esc(e.title)}</strong><p>${esc(e.body)}</p></button>`).join('');}
function timeFormat(seconds){const n=Math.ceil(seconds);return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');}
function renderFocus(){$('coverFocusTime').textContent=timeFormat(S.focus.seconds);$('coverFocusLabel').textContent=S.focus.running?'右滑封面 → 暂停':S.focus.seconds<=0?'已完成 · 左滑重置':'右滑封面 → 开始';if($('focusTime')){$('focusTime').textContent=timeFormat(S.focus.seconds);$('focusDesc').textContent=S.focus.running?'专注正在继续。可以推开这页，在封面上暂停。':'从画面内部下拉开始，或回到活动封面向右滑。';}}
function toggleFocus(){if(S.focus.seconds<=0)S.focus.seconds=900;S.focus.running=!S.focus.running;lastTick=performance.now();renderFocus();save();feedback();}
function resetFocus(){S.focus.running=false;S.focus.seconds=900;renderFocus();save();}
function capHTML(){return [{id:'photo',icon:'picture',name:'给我看',desc:'继续照片 · 调色与版本都留在原处'},{id:'notes',icon:'note',name:'记下来',desc:'新的想法，进入同一份可编辑资料'},{id:'cloud',icon:'cloud',name:'交给我做',desc:'开始一次原文整理 · 本机执行演示'},{id:'focus',icon:'clock',name:'专注一刻',desc:'开始或继续十五分钟'},{id:'talk',icon:'talk',name:'直接交代',desc:'带着当前对象与上下文继续说'}].map(c=>`<button class="cap" data-action="cap" data-cap="${c.id}">${icon(c.icon)}<span><strong>${c.name}</strong><small>${c.desc}</small></span></button>`).join('')+'<div style="display:flex;gap:26px;font-size:11px;margin-top:22px;color:var(--accent)"><button data-action="import">导入照片 ↗</button><button data-action="camera">相机 ↗</button></div>';}
function prepareOverlay(type){if(overlay&&overlay!==type)closeOverlay(true);overlay=type;stopVoice();const e=type==='top'?$('topMenu'):$('launcher');e.classList.add('visible');direct(e,{transform:`translateY(${type==='top'?-H:H}px)`});syncAccess();}
function openOverlay(type){prepareOverlay(type);animateStyle(type==='top'?$('topMenu'):$('launcher'),{transform:'translateY(0)'});report(type==='top'?'顶边 → 系统氛围':'底边 → 能力层',type==='top'?'这是全局系统菜单。内容内部下拉仍只控制当前页面。':'不改动当前任务。向下推回，原内容和页面层级都保留。');}
function closeOverlay(immediate=false){if(!overlay)return;const type=overlay,e=type==='top'?$('topMenu'):$('launcher');overlay='';(immediate?direct:animateStyle)(e,{transform:`translateY(${type==='top'?-H:H}px)`});e.inert=true;setTimeout(()=>{if(overlay!==type)e.classList.remove('visible');},immediate?0:280);syncAccess();}
function lockPhone(sleep=false){if(gesture)finishGesture(null,true);captureSession();stopVoice();if(overlay)closeOverlay(true);locked=true;sleeping=sleep;$('lock').classList.add('visible');direct($('lock'),{transform:'translateX(0)'});$('sleep').classList.toggle('visible',sleeping);syncAccess();clock();}
function wake(){sleeping=false;locked=true;$('sleep').classList.remove('visible');$('lock').classList.add('visible');direct($('lock'),{transform:'translateX(0)'});syncAccess();}
function unlock(){locked=sleeping=false;$('lock').classList.remove('visible');$('sleep').classList.remove('visible');minimize(false);setHome(1,false);syncAccess();report('从锁屏推开 → 活动任务','没有 Home 按钮。双击屏幕可从息屏状态唤醒。');}
function coverAction(id,dir){report('活动封面 → 直接操作','你没有进入任务；封面上的动作已经作用于同一个任务状态。','cover');if(id==='photo')photoNext(dir>0?-1:1);if(id==='cloud'){if(dir>0)toggleJob();else if(S.job.status==='done'){openTask('cloud');pushPage({kind:'result'});}else toast('结果还未完成；向右滑开始或继续');}if(id==='focus'){dir>0?toggleFocus():resetFocus();}if(id==='notes'){if(dir>0){if(window.speechSynthesis){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(S.notes.slice(0,1500));u.lang='zh-CN';speechSynthesis.speak(u);toast('已请求浏览器朗读');}else toast('此浏览器不支持朗读');}else{openTask('notes');exportConfirm('notes');}}}
function coverPreview(id,dx){const e=$('face-'+id),u=$('under-'+id);e.parentElement.classList.add('dragging');let label='',ic='play';if(id==='photo'){label=dx>0?'上一个版本':'下一个版本';ic='picture';}else if(id==='cloud'){label=dx>0?(S.job.status==='running'?'暂停整理':S.job.status==='paused'?'继续整理':'开始整理'):'查看整理结果';ic=dx>0&&S.job.status==='running'?'pause':dx<0?'note':'play';}else if(id==='focus'){label=dx>0?(S.focus.running?'暂停专注':'开始专注'):'重置为 15:00';ic=S.focus.running&&dx>0?'pause':'clock';}else{label=dx>0?'朗读这份笔记':'导出这份笔记';ic='note';}u.innerHTML=icon(ic)+'<span>'+label+'</span>';u.classList.toggle('r',dx<0);direct(e,{transform:`translateX(${clamp(dx,-150,150)}px)`});hint(Math.abs(dx)>=48?'松手：'+label:'继续横滑封面');}
function runMenu(index){const items=menuItems(),item=items[index];if(!item)return;resetPulley();hint('');report('拉绳菜单 → 松手执行',`这一次执行的是「${item.label}」。位置由拉动距离决定，不需要够到按钮。`,'pulley');if(item.action==='export-photo')exportConfirm('photo',{task:currentTask,action:'pulley-action',menu:String(index),pulley:true});else action(item.action);}
async function action(name,el){if(name.startsWith('theme-')){S.theme=name.slice(6);theme();save();feedback();return;}switch(name){case'help':$('helpOverlay').classList.add('open');stopDemo();break;case'help-close':$('helpOverlay').classList.remove('open');break;case'demo':demoRunning?stopDemo():demo();break;case'fullscreen':try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('当前浏览器不支持全屏；仍可直接操作');}setTimeout(fit,60);break;case'power':sleeping?wake():lockPhone(true);break;case'lock':lockPhone();break;case'topmenu':openOverlay('top');break;case'cap':{const id=el.dataset.cap;if(id==='talk'){closeOverlay(true);openTask(currentTask);talk();}else openTask(id);break;}case'event':openTask(el.dataset.target);if(el.dataset.target==='cloud'&&S.job.status==='done')pushPage({kind:'result'});break;case'warm':if(applyEdit('warm'))toast('已加暖，新增一个版本。原图保留。');break;case'history':pushPage({kind:'history'});break;case'export-photo':exportConfirm('photo');break;case'export-note':exportConfirm('notes');break;case'export-result':if(S.job.result)exportConfirm('result');break;case'talk':talk();break;case'send':promptSend();break;case'back':backPage();break;case'accept':acceptDialog();break;case'select-version':S.photo.current=Number(el.dataset.index);renderPhoto();backPage();save();break;case'pulley-action':runMenu(Number(el.dataset.menu));break;case'job-toggle':toggleJob();break;case'job-result':pushPage({kind:'result'});break;case'job-from-note':startOrResumeJob();toast('整理已开始；推开页面，在活动封面看进度');break;case'focus-toggle':toggleFocus();break;case'focus-reset':resetFocus();toast('已重置为 15:00');break;case'sound':S.sound=!S.sound;theme();save();feedback();break;case'motion':S.reduce=!S.reduce;theme();save();break;case'import':choosePhoto('imageInput');break;case'camera':choosePhoto('cameraInput');break;case'backup':downloadText(JSON.stringify(S,null,2),'swipe-ai-backup.json','application/json');toast('本机资料已交给浏览器下载');break;case'voice':voiceEntry();break;}}
// Pointer classifier: edge pushes are system navigation; pulls inside content never silently become them.
function coords(e){const r=$('screen').getBoundingClientRect();if(!r.width||!r.height)return null;return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
function gestureStart(e){if(e.target.closest?.('input,select,[data-range]'))return;if(e.isTrusted&&demoRunning)stopDemo();if(e.button!==undefined&&e.button!==0)return;activePointers.add(e.pointerId);if(activePointers.size>1){finishGesture(null,true);return;}if(gesture)return;const p=coords(e);if(!p)return;const sc=e.target.closest?.('.stack-scroll,.events-list,.talk-history,.home-covers,textarea');gesture={id:e.pointerId,x:p.x,y:p.y,dx:0,dy:0,startAt:performance.now(),target:e.target,cover:e.target.closest?.('.cover')?.dataset.task||'',scroll:sc,scrollTop:sc?.scrollTop||0,edge:p.x<=18?'left':p.x>=W-18?'right':p.y<=16?'top':p.y>=H-18?'bottom':'',mode:'',moved:false,selected:-1,fromPinned:pulleyPinned,startOverlay:overlay,longTimer:null};if(!overlay&&!locked&&!sleeping&&appOpen&&stack.length===0&&!gesture.edge&&!sc&&!e.target.closest('button')){const g=gesture;g.longTimer=setTimeout(()=>{if(gesture===g&&!g.moved){g.mode='longpress';clickBlock=performance.now()+600;talk();feedback();}},600);}}
function chooseMode(g){const ax=Math.abs(g.dx),ay=Math.abs(g.dy),horiz=ax>ay;if(sleeping)return'ignore';if(locked){if(horiz&&['left','right'].includes(g.edge))return'unlock';return'ignore';}if(g.startOverlay)return'overlay-close';if(g.edge==='top'&&g.dy>0){prepareOverlay('top');return'overlay-top';}if(g.edge==='bottom'&&g.dy<0){prepareOverlay('caps');return'overlay-caps';}if(appOpen&&horiz&&(g.edge==='left'&&g.dx>0||g.edge==='right'&&g.dx<0)){setHome(1,false);return'edge-home';}if(appOpen){if(stack.length){if(horiz)return stack.at(-1).kind==='confirm'?'confirm':g.dx>0?'page-back':'page-none';if(g.scroll)return'scroll';return'ignore';}if(g.scroll&&ay>=ax){if(g.target.tagName==='TEXTAREA'||g.scroll.scrollTop>0||g.dy<0)return'scroll';}if(g.dy>0&&!horiz){renderPulley();return'pulley';}if(g.fromPinned&&g.dy<0&&!horiz)return'pulley';if(horiz&&currentTask==='photo'&&g.y>=148&&g.y<572)return'photo-version';if(horiz&&g.dx<0)return'attached';return'ignore';}if(homeIndex===1&&g.cover&&horiz)return'cover';if(g.scroll&&ay>=ax)return'scroll';if(horiz)return'home-pan';return'ignore';}
function gestureMove(e){const g=gesture;if(!g||g.id!==e.pointerId||g.mode==='longpress')return;const p=coords(e);if(!p){finishGesture(null,true);return;}g.dx=p.x-g.x;g.dy=p.y-g.y;if(!g.moved&&Math.hypot(g.dx,g.dy)<8)return;if(!g.moved){g.moved=true;$('toast').classList.remove('show');clearTimeout(g.longTimer);g.mode=chooseMode(g);try{$('screen').setPointerCapture(e.pointerId);}catch{}}if(e.cancelable)e.preventDefault();const dx=g.dx,dy=g.dy;switch(g.mode){case'edge-home':{const signed=g.edge==='left'?Math.max(0,dx):Math.min(0,dx);direct($('task'),{transform:`translate3d(${clamp(signed,-W,W)}px,0,0)`});$('peekCaption').classList.add('show');const n=Math.abs(signed);hint(n>W*.36?'松手回活动任务 · 推回则继续原内容':'Peek：不松手，可以推回原处');report('边缘推开 → 半滑窥视','界面跟随手指；背后的封面不是截屏，进度会继续变化。');break;}case'unlock':direct($('lock'),{transform:`translateX(${clamp(dx,-W,W)}px)`});break;case'home-pan':{const t=clamp(-homeIndex*W+dx,-2*W-40,40);direct($('systemTrack'),{transform:`translateX(${t}px)`});hint('事件 ← 活动任务 → 发起能力');break;}case'cover':coverPreview(g.cover,dx);break;case'pulley':pulleyPreview((g.fromPinned?230:0)+dy);break;case'photo-version':{if($('photoStage'))direct($('photoStage'),{transform:`translateX(${clamp(dx,-W*.45,W*.45)}px)`});hint(dx<0?'松手：下一个版本':'松手：上一个版本');break;}case'page-back':if(topPage())direct(topPage(),{transform:`translateX(${Math.max(0,dx)}px)`});hint(dx>110?'松手回到父页面':'内容右滑：回上一层');break;case'confirm':if(topPage())direct(topPage(),{transform:`translateX(${clamp(dx,-W*.65,W*.65)}px)`});hint(Math.abs(dx)<110?'左滑接受 · 右滑取消':dx<0?'松手：接受此固定内容':'松手：取消');break;case'attached':hint(currentTask==='photo'?'松手进入版本记录':'松手继续交代');break;case'overlay-top':direct($('topMenu'),{transform:`translateY(${-H+clamp(dy,0,H)}px)`});hint('顶边 → 全局系统菜单');break;case'overlay-caps':direct($('launcher'),{transform:`translateY(${H+clamp(dy,-H,0)}px)`});hint('底边 → 能力层');break;case'overlay-close':{const e=g.startOverlay==='top'?$('topMenu'):$('launcher');const d=g.startOverlay==='top'?Math.min(0,dy):Math.max(0,dy);direct(e,{transform:`translateY(${d}px)`});break;}case'scroll':g.scroll.scrollTop=g.scrollTop-viewY(dy);break;}}
function finishGesture(e,cancel=false){const g=gesture;if(e)activePointers.delete(e.pointerId);if(!g||e&&g.id!==e.pointerId)return;gesture=null;clearTimeout(g.longTimer);hint('');$('peekCaption').classList.remove('show');if(g.moved||g.mode==='longpress')clickBlock=performance.now()+400;try{if($('screen').hasPointerCapture(g.id))$('screen').releasePointerCapture(g.id);}catch{}const dx=g.dx,dy=g.dy;switch(g.mode){case'edge-home':{const d=g.edge==='left'?Math.max(0,dx):Math.max(0,-dx);if(!cancel&&d>W*.36){captureSession();appOpen=false;animateStyle($('task'),{transform:`translateX(${dx>=0?W:-W}px)`},230);syncAccess();const taskId=currentTask;setTimeout(()=>{if(!appOpen&&currentTask===taskId){$('task').classList.remove('open');direct($('task'),{transform:'translateX(0)'});}},235);report('内容退到封面，任务没有退出','现在直接横滑封面，不必再次进入任务。','home');}else{animateStyle($('task'),{transform:'translateX(0)'});report('Peek 完成，原内容仍在原处','没有重建页面，没有改动版本，也没有丢掉草稿。',cancel?null:'peek');}break;}case'unlock':if(!cancel&&Math.abs(dx)>110)unlock();else animateStyle($('lock'),{transform:'translateX(0)'});break;case'home-pan':setHome(!cancel&&Math.abs(dx)>75?homeIndex+(dx<0?1:-1):homeIndex);if(!cancel)report('三视图有固定空间关系','左边是事件，中间是活动任务，右边是发起能力；不是三个应用互相翻页。');break;case'cover':animateStyle($('face-'+g.cover),{transform:'translateX(0)'});setTimeout(()=>$('face-'+g.cover).parentElement.classList.remove('dragging'),275);if(!cancel&&Math.abs(dx)>=48)coverAction(g.cover,Math.sign(dx));break;case'pulley':{const d=(g.fromPinned?230:0)+dy;if(!cancel&&d>=258){pinPulley();}else if(!cancel&&d>=68){runMenu(clamp(Math.floor((d-68)/56),0,2));}else resetPulley();break;}case'photo-version':if($('photoStage'))animateStyle($('photoStage'),{transform:'translateX(0)'});if(!cancel&&Math.abs(dx)>65){photoNext(dx<0?1:-1);report('内部横滑，只比较版本','你还在同一张图片里；从边缘开始才会回活动任务。');}break;case'page-back':if(!cancel&&dx>110)backPage();else if(topPage())animateStyle(topPage(),{transform:'translateX(0)'});break;case'confirm':if(!cancel&&Math.abs(dx)>110){dx<0?acceptDialog():backPage();}else if(topPage())animateStyle(topPage(),{transform:'translateX(0)'});break;case'attached':if(!cancel&&dx< -90){if(currentTask==='photo')pushPage({kind:'history'});else if(currentTask==='cloud')pushPage({kind:'result'});else talk();}break;case'overlay-top':if(!cancel&&dy>125){animateStyle($('topMenu'),{transform:'translateY(0)'});}else closeOverlay();break;case'overlay-caps':if(!cancel&&dy< -125){animateStyle($('launcher'),{transform:'translateY(0)'});}else closeOverlay();break;case'overlay-close':if(!cancel&&(g.startOverlay==='top'&&dy< -90||g.startOverlay==='caps'&&dy>90||Math.abs(dx)>120))closeOverlay();else animateStyle(g.startOverlay==='top'?$('topMenu'):$('launcher'),{transform:'translateY(0)'});break;}syncAccess();}
$('screen').addEventListener('pointerdown',gestureStart);
$('screen').addEventListener('pointermove',gestureMove,{passive:false});
window.addEventListener('pointerup',e=>finishGesture(e));
window.addEventListener('pointercancel',e=>finishGesture(e,true));
// Touch starts with implicit capture on the child. Its loss during transfer
// to the screen is not cancellation; only losing the screen's own capture is.
$('screen').addEventListener('lostpointercapture',e=>{if(e.target===$('screen')&&gesture?.id===e.pointerId&&!$('screen').hasPointerCapture(e.pointerId))finishGesture(e,true);});
$('screen').addEventListener('dblclick',e=>{if(sleeping){wake();e.preventDefault();}});
document.addEventListener('click',e=>{const inScreen=$('screen').contains(e.target);if(inScreen&&performance.now()<clickBlock){e.preventDefault();e.stopPropagation();return;}const el=e.target.closest('[data-action]');if(el){action(el.dataset.action,el);return;}if(sleeping||locked||overlay)return;if(inScreen&&appOpen&&pulleyPinned){resetPulley();return;}const cover=e.target.closest('.cover');if(cover&&!appOpen&&homeIndex===1){openTask(cover.dataset.task);return;}if(appOpen&&stack.length===0&&currentTask==='photo'&&e.target.closest('#photoStage'))selectPhoto(e);},true);
$('screen').addEventListener('input',e=>{if(e.target.id==='noteEditor'){S.notes=e.target.value;renderNoteCover();save();}if(e.target.id==='talkInput'){S.drafts[currentTask]=e.target.value;save();}});
$('imageInput').addEventListener('change',e=>{fileChosen(e.target.files[0]);e.target.value='';});$('cameraInput').addEventListener('change',e=>{fileChosen(e.target.files[0]);e.target.value='';});
for(const id of ['imageInput','cameraInput'])$(id).addEventListener('cancel',()=>{photoPickerOrigin=null;});
document.addEventListener('keydown',e=>{if(confirmationKey(e))return;if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&document.activeElement.id==='talkInput'){e.preventDefault();promptSend();}return;}if($('helpOverlay').classList.contains('open')){if(e.key==='Escape')$('helpOverlay').classList.remove('open');return;}if(e.key==='Escape'){e.preventDefault();if(demoRunning){stopDemo();return;}if(overlay)closeOverlay();else if(pulleyPinned)resetPulley();else if(stack.length&&appOpen)backPage();else if(appOpen)minimize();return;}if(locked||sleeping){if(e.key==='Enter'){sleeping?wake():unlock();e.preventDefault();}return;}if(e.key===' '&&document.activeElement?.tagName==='BUTTON')return;const k=e.key.toLowerCase();if(k==='h'){e.preventDefault();if(overlay)closeOverlay();minimize();setHome(1);}if(k==='m'){e.preventDefault();pinPulley();}if(k==='a'){e.preventDefault();openOverlay('caps');}if(k==='e'){e.preventDefault();minimize(false);setHome(0);}if(k==='t'){e.preventDefault();openOverlay('top');}if(k===' '){e.preventDefault();if(currentTask==='focus'&&appOpen)toggleFocus();else toggleJob();}if(e.key==='Enter'&&document.activeElement?.classList.contains('cover'))openTask(document.activeElement.dataset.task);});
window.addEventListener('blur',()=>{if(gesture)finishGesture(null,true);activePointers.clear();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pauseJob();S.focus.running=false;stopVoice();saveNow();}lastTick=performance.now();});
window.addEventListener('pagehide',()=>{if(S.job.status==='running')S.job.status='paused';S.focus.running=false;stopVoice();saveNow();});
setInterval(()=>{const now=performance.now(),dt=Math.min((now-lastTick)/1000,1.5);lastTick=now;if(document.hidden)return;if(S.job.status==='running'){jobClock+=dt;if(jobClock>=.85){jobClock=0;jobStep();}}if(S.focus.running){S.focus.seconds=Math.max(0,S.focus.seconds-dt);renderFocus();focusSaveClock+=dt;if(focusSaveClock>3){focusSaveClock=0;save();}if(S.focus.seconds<=0){S.focus.running=false;addEvent('专注一刻完成','这段十五分钟留给了眼前的事情。','focus');toast('十五分钟专注已完成');save();}}},200);
// Guided replay uses the same pointer state machine as manual gestures, not a video or screenshot.
function stopDemo(){demoToken++;demoRunning=false;if(gesture)finishGesture(null,true);activePointers.clear();$('finger').classList.remove('show');$('trainingStrip').classList.remove('show');$('screen').classList.remove('learning');$('demoTop').textContent='看手势演示';$('demoButton').innerHTML='看一遍，跟着手势走'+icon('arrow');}
function delay(ms){return new Promise(r=>setTimeout(r,ms));}
function demoCaption(text){$('trainingStrip').textContent=text;$('trainingStrip').classList.add('show');}
function synthetic(type,x,y){const r=$('screen').getBoundingClientRect();const cx=r.left+x*r.width/W,cy=r.top+y*r.height/H;const e=new PointerEvent(type,{bubbles:true,cancelable:true,clientX:cx,clientY:cy,pointerId:909,pointerType:'mouse',isPrimary:true,button:0,buttons:type==='pointerup'?0:1});const target=type==='pointerdown'?document.elementFromPoint(cx,cy):$('screen');(target||$('screen')).dispatchEvent(e);$('finger').style.left=viewX(x)+'px';$('finger').style.top=viewY(y)+'px';}
async function dragDemo(points,token){if(token!==demoToken)throw Error('stopped');$('finger').classList.add('show');synthetic('pointerdown',points[0][0],points[0][1]);for(let i=1;i<points.length;i++){const [x0,y0]=points[i-1],[x1,y1,ms=600]=points[i];const n=Math.max(1,Math.round(ms/22));for(let k=1;k<=n;k++){if(token!==demoToken)throw Error('stopped');synthetic('pointermove',x0+(x1-x0)*k/n,y0+(y1-y0)*k/n);await delay(ms/n);}}const p=points.at(-1);synthetic('pointerup',p[0],p[1]);$('finger').classList.remove('show');await delay(340);}
async function demo(){if(!ready){toast('正在准备画面');return;}stopDemo();$('helpOverlay').classList.remove('open');const token=demoToken;demoRunning=true;$('screen').classList.add('learning');$('demoTop').textContent='停止演示';$('demoButton').innerHTML='停止演示'+icon('pause');try{if(locked||sleeping)unlock();closeOverlay(true);openTask('photo',{noAnimation:true});stack=[];renderStack();resetPulley(false);demoCaption('① 边缘推开一半，再推回去：只是看一眼。');await delay(900);await dragDemo([[4,350],[167,350,950],[167,350,750],[5,350,950]],token);demoCaption('② 再从边缘推开并松手：退到活动封面。');await delay(500);await dragDemo([[4,350],[275,350,1200]],token);demoCaption('③ 右滑整理封面：不打开任务，也能开始执行。');await delay(600);await dragDemo([[209,233],[315,233,1100]],token);await delay(1300);if(token!==demoToken)throw Error('stopped');openTask('photo');stack=[];renderStack();demoCaption('④ 从内容内部下拉，松手执行「暖一点」。');await delay(600);await dragDemo([[172,244],[172,340,1500]],token);await delay(1300);demoCaption('⑤ 顶部边缘下拉：这次打开的是系统氛围。');await dragDemo([[174,5],[174,251,1200]],token);await delay(900);await dragDemo([[181,433],[181,192,900]],token);report('现在，换你推开看看。','边缘是系统，内部是内容；照片已经新增暖调版本，整理任务状态也留在封面上。');await delay(600);}catch(e){if(e.message!=='stopped')console.error(e);}finally{if(token===demoToken)stopDemo();}}
window.SwipeDiagnostics={version:'3.0.0',snapshot:()=>({ready,appOpen,currentTask,homeIndex,stack:stack.map(s=>s.kind),overlay,locked,sleeping,pulleyPinned,gesture:gesture?{mode:gesture.mode,dx:gesture.dx,dy:gesture.dy}:null,photo:{current:S.photo.current,versions:S.photo.versions.length,selection:S.photo.selection},job:{status:S.job.status,progress:S.job.progress,result:S.job.result},focus:{...S.focus},notes:S.notes,theme:S.theme,drafts:{...S.drafts},learned:[...learned],demoRunning}),state:()=>JSON.parse(JSON.stringify(S))};
async function init(){fit();clock();theme();if(storageIssue)$('storageError').hidden=false;const sample=makeSample();document.documentElement.style.setProperty('--wall',`url("${sample.toDataURL('image/jpeg',.78)}")`);baseCanvas=sample;if(S.photo.source){try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=S.photo.source;});if(img.naturalWidth*img.naturalHeight>16000000)throw Error('size');baseCanvas=document.createElement('canvas');baseCanvas.width=img.naturalWidth;baseCanvas.height=img.naturalHeight;baseCanvas.getContext('2d').drawImage(img,0,0);}catch{S.photo=defaults().photo;toast('保存的图片读取失败，已恢复示例');}}$('capsList').innerHTML=$('launcherList').innerHTML=capHTML();renderPhoto();renderNoteCover();renderJob();renderFocus();renderEvents();renderRoot();setHome(1,false);syncAccess();ready=true;setInterval(clock,15000);setTimeout(fit,150);}
init().catch(e=>{console.error(e);toast('启动未完成，请重新打开文件');});
