/*
 * Complete UI suite, composed on the accepted V3 gesture engine.
 * A route is not an application. Sources, drafts and approvals have explicit state.
 * Only deterministic local operations run here. Remote services remain disconnected.
 */
(function(){
'use strict';
const catalog=window.UI_CATALOG;
const routes=new Map(catalog.map(r=>[r.id,r]));
const STORE_UI='ai-phone-ui-suite-v1';
let D=PhoneModel.initial();
let uiStorageWarned=false,renderingRoute='SYS-01';
try{const raw=localStorage.getItem(STORE_UI);if(raw)D=PhoneModel.validate(JSON.parse(raw));}catch{uiStorageWarned=true;}
let activeRoute='SYS-01',viewState='default',pendingRestore=null,lastDeleted=null,selectedDay=new Date().getDate(),monthOffset=0;
let callMuted=false,callSpeaker=false,playingPreview=false;
const rootForTask=new Map(),liveRouteForTask=new Map();
const row=(title,sub='',target='',glyph='arrow',extra='')=>`<${target?'button':'div'} class="s-row" ${target?`data-action="ui:go:${target}"`:''}>${glyph?icon(glyph):''}<span class="grow"><b>${esc(title)}</b>${sub?`<small>${esc(sub)}</small>`:''}</span>${extra|| (target?'<span class="chev">›</span>':'')}</${target?'button':'div'}>`;
const button=(label,action,kind='')=>`<button class="s-button ${kind}" data-action="ui:${action}">${esc(label)}</button>`;
const note=(content,warn=false)=>`<div class="s-notice ${warn?'warn':''}">${esc(content)}</div>`;
const chip=(label,action,on=false)=>`<button class="s-chip ${on?'active':''}" data-action="ui:${action}">${esc(label)}</button>`;
const savedField=(name,value)=>D.forms?.[renderingRoute]?.[name]??value;
const field=(label,name,value='',placeholder='',type='text')=>`<label class="s-form">${esc(label)}<input data-field="${name}" value="${esc(savedField(name,value))}" placeholder="${esc(placeholder)}" type="${type}" maxlength="${type==='text'?300:100}" autocomplete="off"></label>`;
const area=(label,name,value='',placeholder='')=>`<label class="s-form">${esc(label)}<textarea data-field="${name}" placeholder="${esc(placeholder)}" maxlength="10000">${esc(savedField(name,value))}</textarea></label>`;
const select=(label,name,options,value)=>`<label class="s-form">${esc(label)}<select data-field="${name}">${options.map(x=>`<option ${x===savedField(name,value)?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`;
const toggle=(label,sub,key,value)=>`<button class="s-row" data-action="ui:toggle:${key}" role="switch" aria-checked="${!!value}"><span class="grow"><b>${esc(label)}</b><small>${esc(sub)}</small></span><span class="s-switch ${value?'on':''}"></span></button>`;
const steps=(items,current=0)=>items.map((x,i)=>`<div class="s-task-step"><span class="s-step-num">${i<current?'✓':i+1}</span><div><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div></div>`).join('');
const message=(who,body)=>`<div class="s-message ${who==='你'?'user':'ai'}"><small>${esc(who)}</small>${esc(body)}</div>`;
const wave=()=>`<div class="s-wave" aria-label="音频波形示意">${[14,25,37,57,34,66,76,49,30,58,77,64,31,55,47,27,17].map(h=>`<i style="height:${h}px"></i>`).join('')}</div>`;
const getDraft=(key,fallback='')=>D.drafts[key]??fallback;
const persist=()=>{try{localStorage.setItem(STORE_UI,JSON.stringify(D));}catch{uiStorageWarned=true;if($('storageError'))$('storageError').hidden=false;}};
function log(title,detail=''){D.audit.unshift({id:uid(),title,detail,at:Date.now()});D.audit=D.audit.slice(0,120);persist();}
function applyPrefs(){document.body.classList.toggle('large-text',D.settings.largeText);document.body.classList.toggle('high-contrast',D.settings.contrast);$('suiteAssist')?.classList.toggle('show',D.settings.assist);}
function current(){if(sleeping)return routes.get('SYS-06');if(locked)return routes.get('SYS-05');if(overlay)return routes.get(overlay==='top'?'SYS-04':'SYS-03');if(!appOpen)return routes.get(['SYS-02','SYS-01','SYS-03'][homeIndex]);const top=stack.at(-1);if(top?.kind==='suite')return routes.get(top.routeId);if(rootForTask.has(currentTask))return routes.get(rootForTask.get(currentTask));return routes.get(activeRoute);}
function sourceImage(original=false){if(!baseCanvas)return '';return (original?baseCanvas:versionCanvas(S.photo.versions[S.photo.current])).toDataURL('image/jpeg',.78);}
function imageTag(original=false,extra=''){return `<img ${extra} src="${sourceImage(original)}" alt="${original?'原始素材':'当前编辑版本'}">`;}
function headerFor(r){return `<div class="app-header suite-header"><div class="eyebrow"><span>${esc(r.id)} / ${esc(r.group)}</span><span class="mode-chip ${r.mode==='prototype'?'preview':''}">${r.mode==='prototype'?'交互预览 · 未连接':'本机可操作'}</span></div><h2>${esc(r.name)}</h2><div class="metadata">${esc(r.purpose)}</div></div>`;}
const fixtures={contacts:[['小林','产品讨论'],['小陈','设计评审'],['测试联系人','仅用于 UI 预览']],article:'让内容站在交互的中央\n\n一次操作可以从现实中的对象开始，也可以从一句未完成的话开始。\n\n把照片推开，任务并未消失。内容让出前台，进度、版本和想法仍在原处。\n\n不同能力通过清楚的执行契约合作。界面必须告诉使用者：什么已完成，什么只是草稿，什么仍在等待许可。\n\n这是为界面测试编写的本地示例文章，不是联网获取的新闻。'};
function bodyFor(r){
renderingRoute=r.id;const type=r.type;let html='';
switch(type){
case 'welcome':return `<div class="s-hero"><div class="orb-small"></div><div class="s-flow-tag">SWIPE / AI</div><div class="s-title-large">不用找应用。<br>从眼前，接着来。</div></div>${note('这是 UI 项目的本机交互版。真实 AI、云端 Android 与外部服务均未连接。')}${button('设置我的体验','go:ONB-02','primary')}${button('直接进入活动任务','go:SYS-01')}${row('先学三个动作','边缘推开 / 半滑窥视 / 内容下拉','ONB-04','arrow')}`;
case 'consent':return `<h3>开始之前，你来决定。</h3><p>浏览内容不需要授权。每项能力在真正使用时再次请求；这里保存的只是你的偏好。</p>${toggle('相机使用意向','使用相机前仍会请求设备权限','consent.camera',D.consent.camera)}${toggle('语音输入意向','浏览器识别可能依赖在线服务','consent.microphone',D.consent.microphone)}${toggle('任务提示意向','当前版本只显示网页内提示','consent.notifications',D.consent.notifications)}${button('保存偏好，继续','go:ONB-03','primary')}${row('了解数据如何保存','无遥测、无默认上传','SET-09','lock')}`;
case 'profile':return `<div class="s-avatar s-hero-avatar">我</div>${field('怎么称呼你','nickname',D.nickname,'输入昵称')}${note('这只是本机资料，不代表已经创建云端账户。无需填写手机号或密码。')}${button('保存并练习手势','save-profile','primary')}${row('跳过设置','保留默认昵称','ONB-04','arrow')}`;
case 'training':return `${steps([['从边缘推开','把整件事收回活动封面，不停止后台步骤。'],['推到一半再推回','不松手就能窥视，原来内容和草稿不会重建。'],['从内容里向下拉','按距离选择动作；往回推可以取消。'],['横滑活动封面','不打开任务，也能直接暂停或继续。']])}${button('看一遍真实手势演示','demo','primary')}${button('进入练习照片','go:IMG-02')}${row('继续设置个人环境','云端开通界面预览','ONB-05','cloud')}`;
case 'enrollment':return `<div class="s-env-status"><span class="s-status-dot"></span>云端未连接</div><div class="s-metric">01 <small>/ 03</small></div>${steps([['选择存放区域','连接服务后由服务端返回可选区域。'],['创建个人环境','需要后端隔离、加密和任务执行器。'],['绑定当前设备','生成设备授权和可撤销会话。']],0)}${note('此处不会创建收费实例或申请 Android 环境。可以先使用本机交互。',true)}${button('查看云端环境设计','go:CLD-01','primary')}${button('进入本机体验','go:SYS-01')}`;
case 'conversation':return `<div class="s-env-status"><span class="s-status-dot local"></span>本机规则 · 没有接入模型</div><div class="s-conversation-log stack-scroll" style="position:relative;inset:auto">${D.messages.length?D.messages.slice(-12).map(m=>message(m.role==='user'?'你':'本机助手',m.text)).join(''):message('本机助手','我会保留当前照片和笔记的上下文。试试「记下：新的想法」「照片暖一点」或「开始整理」。')}</div>${area('继续交代','prompt',getDraft('AI-01'),'输入你的要求…')}<div class="s-actions">${button('查看上下文','go:AI-08')}${button('发送','prompt','primary')}</div>${row('语音表达','先授权，结果校对后再发送','AI-02','mic')}${row('执行计划与确认','查看需要多步骤服务的交互设计','AI-04','list')}`;
case 'listening':return `<div class="s-hero">${wave()}<div class="s-title-large">现在，只听你说。</div></div>${note('波形是状态预览，尚未开启麦克风。点击下方按钮后才调用浏览器语音识别。',true)}${button('请求浏览器语音输入','voice','primary')}${area('识别后的可编辑文字','transcribed',getDraft('AI-02'),'识别结果应先填入这里，允许纠正')}<div class="s-actions">${button('取消','go:AI-01')}${button('作为文字草稿','use-transcript')}</div>`;
case 'thinking':return `<div class="s-hero"><div class="s-spinner"></div><div class="s-title-large">把事情拆开，<br>再一步步完成。</div></div>${steps([['理解当前对象','照片与笔记的来源随任务保存。'],['选择合适能力','当前未连接模型，以下为状态预览。'],['等待执行结果','只有服务回执才能代表动作已完成。']],1)}${button('停止这次预览','stop-preview')}${row('查看执行计划','停止后草稿仍然保留','AI-04','arrow')}`;
case 'plan':return `<h3>为这张照片准备封面</h3>${steps([['保护原始素材','保留人物和衣服，原图不覆盖。'],['生成两个候选','需要图像生成服务；现在只保存要求。'],['由你选择版本','比较结果，允许继续修改。'],['确认后导出或发送','发送前固定内容、目标与授权。']])}${area('补充要求','planNote',getDraft('AI-04'),'例如：不要重绘人物脸部')}<div class="s-actions">${button('修改生成要求','go:IMG-06')}${button('审阅执行范围','go:AI-05','primary')}</div>`;
case 'approval':return `<div class="s-label">待确认 / 不会实际发送</div><h3>交付这一份内容</h3>${row('内容','当前照片 · '+S.photo.versions[S.photo.current].label,'IMG-03','picture')}${row('接收方','示例联系人小林 · 非真实联系人','','talk')}${row('允许的动作','预览一次发送，不能再次执行','','lock')}${note('确认只保存本机审批预览记录。没有发送消息、上传图片或调用任何外部服务。',true)}${button('审阅并进入手势确认','confirm-approval','primary')}${button('返回修改','go:AI-04')}`;
case 'deliverable':return `<div class="s-label">本机成果</div><h3>整理好的内容在这里</h3><div class="s-document">${esc(S.job.result||S.notes)}</div>${button('导出当前文字快照','export-document','primary')}${row('查看原始输入','每条结果都应有输入来源','AI-08','note')}`;
case 'history':return `${note('记录来自本机规则会话，不代表真实模型推理日志。')}${D.messages.length?D.messages.slice(-16).map(m=>message(m.role==='user'?'你':'本机助手',m.text)).join(''):row('还没有新的会话','输入第一条要求开始','AI-01','talk')}${button('继续这段会话','go:AI-01','primary')}`;
case 'context':return `<h3>这次正在用什么</h3>${row(S.photo.name,'照片 · 当前版本 '+S.photo.versions[S.photo.current].label,'IMG-02','picture')}${row('我的想法',S.notes.length+' 字 · 本机原文','DOC-02','note')}${row('已确认偏好',D.memories.filter(m=>m.enabled).length+' 条，来自明确设置','SET-07','check')}${note('这里展示输入，不展示模型的隐藏推理。原始记录、用户偏好和生成内容必须分开。')}${button('回去继续交代','go:AI-01','primary')}`;
case 'camera':return `<div class="s-camera">${imageTag(true)}<div class="grid"></div><div class="reticle"></div><span class="tag">构图示例 · 不是实时取景</span></div><div class="s-actions">${chip('记录模式','camera-mode-record',true)}${chip('创作模式','go:IMG-06')}</div>${button('使用设备相机 / 选取照片','camera','primary')}${button('从本机导入','import')}${note('拍摄入口依浏览器和设备支持情况调用系统相机。不会在你操作前打开摄像头。')}${row('使用当前示例继续','不申请任何权限','IMG-02','picture')}`;
case 'crop':{const [a,b]=D.cropRatio.split(':').map(Number);const wide=a/b;const w=wide>=1?260:235*wide,h=wide>=1?260/wide:235;return `<div class="s-crop-stage">${imageTag()}<div class="s-crop-outline" style="width:${w}px;height:${h}px"></div></div><div>${['1:1','4:3','3:4','16:9','9:16'].map(x=>chip(x,'crop-ratio:'+x,D.cropRatio===x)).join('')}</div>${note('以画面中央裁切，输出新 PNG；原图和已有编辑版本不被改动。')}${button('导出裁切副本','crop-export','primary')}${row('返回完整照片','后续版本将扩展拖动取景框','IMG-02','picture')}`;}
case 'generate':return `${area('想得到什么','generationPrompt',getDraft('IMG-06',D.generatedDraft),'保留人物和衣服，背景改为雨夜…')}${row('锁定的内容','当前示例主体和原始素材','','lock')}${select('输出构图','generationFormat',['竖屏 9:16','方形 1:1','横向 16:9'],'竖屏 9:16')}${toggle('保留原始记录','本机原片始终保留','protect-original',true)}${note('尚未连接图像生成服务。下一步只保存要求并展示队列 UI，不会生成新场景。',true)}${button('保存要求，查看队列','generation-queue','primary')}`;
case 'generation':return `<div class="s-label">示例任务 / 未调用生成服务</div><h3>雨夜封面 · 两个候选</h3><div class="s-metric">— <small>等待服务接入</small></div>${steps([['输入素材已就位','只引用本机当前照片。'],['生成要求已保存',D.generatedDraft||'还没有输入新的生成要求。'],['候选图像尚未生成','本机调色结果不能冒充生成式图像。']],2)}${button('返回修改要求','go:IMG-06','primary')}${button('取消队列预览','cancel-generation')}${row('查看失败与重试设计','失败时保留输入和版本','ERR-02','arrow')}`;
case 'compare':return `<div class="s-compare" id="suiteComparison" style="--compare:${D.comparison}%">${imageTag(true)}${imageTag(false,'class="edited"')}<div class="divider"></div></div><div class="compare-labels"><span>原图</span><span>${esc(S.photo.versions[S.photo.current].label)}</span></div><label class="s-form">拖动分隔线<input class="s-range" type="range" min="0" max="100" value="${D.comparison}" data-range="compare" aria-label="原图对比比例"></label>${row('换一个历史版本','回到照片内部横滑','IMG-03','history')}${button('收好当前版本','go:IMG-09','primary')}`;
case 'gallery':return `${note('显示当前本机照片的编辑版本，不读取系统相册。') }<div class="s-gallery">${S.photo.versions.map((v,i)=>`<button data-action="ui:gallery-select:${i}"><img src="${versionCanvas(v).toDataURL('image/jpeg',.5)}" alt="${esc(v.label)}"><span>${esc(v.label)} ${i===S.photo.current?'✓':''}</span></button>`).join('')}</div>${button('导入其他照片','import')}`;
case 'library':case 'files':return `${row(S.photo.name,'图像 · '+S.photo.versions.length+' 个版本','IMG-10','picture')}${row('我的想法',S.notes.length+' 字 · 自动保存在本机','DOC-02','note')}${row('整理结果',S.job.result?'已生成本机整理稿':'尚未整理','DOC-04','cloud')}${row('备份资料包','包含本机照片、笔记与偏好','CLD-17','download')}${note('这里只展示本机数据。云端存储尚未连接，不显示虚构的已同步状态。')}`;
case 'checklist':{const items=D.checklist.length?D.checklist:PhoneModel.extractChecklist(S.notes);return `<p>来自当前笔记的非空条目。勾选状态只在本机保存。</p>${items.map((x,i)=>`<label class="s-check"><input type="checkbox" data-check-id="${i}" ${x.done?'checked':''}><span>${esc(x.text)}</span></label>`).join('')}${button('从当前笔记重新提取','refresh-checklist')}${button('导出清单','export-checklist','primary')}`;}
case 'document':return `<div class="s-label">${S.job.result?'本机整理结果':'当前原文 · 尚未整理'}</div><div class="s-document">${esc(S.job.result||S.notes)}</div>${button('导出当前内容','export-document','primary')}${row('返回输入来源','我的想法','DOC-02','note')}`;
case 'recorder':return `<div class="s-hero"><div class="s-metric">00:00</div>${wave()}<p>收音前，先确定记录范围。</p></div>${field('这段录音的标题','recordName',getDraft('DOC-05'),'例如：一次产品讨论')}${note('当前只有录音界面预览，不会后台采集。语音识别入口会另行请求授权。',true)}${button('体验浏览器语音输入','voice','primary')}${row('查看转写校对设计','片段、说话人和原音定位','DOC-06','note')}`;
case 'transcript':return `${note('以下是人工编写的界面样例，不是对你的音频进行转写。',true)}${[['00:00','说话人 A','我们希望从内容出发，而不是从应用图标出发。'],['00:12','说话人 B','先把这张照片推开，看看后台任务。'],['00:26','说话人 A','然后在同一段上下文中接着修改。']].map(([t,s,x])=>`<div class="s-task-step"><span class="muted">${t}</span><div><strong>${s}</strong><p>${x}</p></div></div>`).join('')}${area('可校对文字','transcriptText',getDraft('DOC-06'),'写下校对后的内容')}${button('把校对文字追加到笔记','save-transcript','primary')}`;
case 'runtime':return `<div class="s-env-status"><span class="s-status-dot"></span>云端未连接 · 本机体验可用</div><div class="s-hero"><div class="orb-small"></div><h3>${esc(D.nickname)}的个人环境</h3><p>资料有自己的位置。任务有可以接续的状态。</p></div>${row('执行中的事情','本机整理与远端任务的设计分开','CLD-02','cloud')}${row('文件空间','当前只有本机资料','CLD-06','note')}${row('服务与授权','所有外部服务均未连接','CLD-08','lock')}${row('设备与恢复','端侧状态持久化，云端待接入','CLD-14','arrow')}${row('用量与预算','界面模型，不是实际账单','CLD-15','list')}`;
case 'jobs':return `${row('整理我的想法',`本机真实步骤 · ${S.job.status==='done'?'已完成':S.job.status==='running'?'运行中':S.job.status==='paused'?'已暂停':'待开始'}`,'CLD-03','cloud')}${row('雨夜封面生成','交互预览 · 等待模型接入','IMG-07','picture')}${row('发送成果给联系人','交互预览 · 等待确认','CLD-05','talk')}${row('周期任务草稿',D.schedules.length+' 个本机草稿，均未运行','CLD-11','clock')}${button(S.job.status==='running'?'暂停本机整理':'开始 / 继续本机整理','job-toggle','primary')}`;
case 'job':return `<div class="s-env-status">同一个本机整理任务 · 不是云端服务</div><div class="s-metric"><span data-suite-job="percent">${Math.round(S.job.progress)}</span><small>%</small></div><div class="s-track"><i data-suite-job="meter" style="width:${S.job.progress}%"></i></div><p data-suite-job="status">${({idle:'等待开始',running:'正在处理原文快照',paused:'已暂停，进度保留',done:'整理已完成'})[S.job.status]}</p>${button(S.job.status==='running'?'暂停本机整理':'开始 / 继续本机整理','job-toggle','primary')}${row('执行步骤','读取、提取与组装','CLD-04','list')}${row('原文与结果','保留本次输入来源','DOC-04','note')}${note('网页关闭或隐藏后暂停。不会把动画当成真实云端处理。')}`;
case 'steps':return `${steps([['读取笔记快照',S.job.source?S.job.source.length+' 字已作为此次输入':'等待开始整理。'],['提取与去重','当前 '+(S.job.cursor||0)+' / '+S.job.lines.length+' 条。'],['组装文档','输出的是原文整理，不是 AI 推理或改写。']],S.job.status==='done'?3:S.job.cursor>0?1:0)}${button(S.job.status==='running'?'暂停整理':'开始 / 继续','job-toggle','primary')}${row('查看原文与结果','保留本次输入快照','DOC-04','note')}`;
case 'approvals':return `${note('以下是待确认动作的设计样例。没有真实待发送的消息或订单。',true)}${row('发送这张封面','内容与接收方需要你确认','AI-05','talk')}${row('授权一个新服务','一次许可、有限权限、可撤销','CLD-09','lock')}${row('删除一条偏好','说明删除范围并允许撤销','ERR-08','trash')}`;
case 'file':return `<div class="s-art">${imageTag()}</div>${row(S.photo.name,'类型：本机图片','','picture')}${row('版本与来源',S.photo.versions.length+' 个版本，原片未覆盖','IMG-03','history')}${row('存放位置','当前浏览器本机空间','','lock')}${button('导出当前版本','go:IMG-09','primary')}${row('全量备份','导出图像、笔记与偏好','CLD-17','download')}`;
case 'services':return `<p>能力以接口提供。AI 不需要替你一层层操作图形界面。</p>${['图像生成服务','日历服务','消息服务','文件空间','Android 兼容环境'].map((x,i)=>row(x,'未连接 · 需要对应服务端适配','CLD-09',['picture','clock','talk','note','cloud'][i])).join('')}${note('这个 UI 项目不包含服务端登录、凭据保存或第三方账户操作。')}`;
case 'service':return `<h3>连接一个能力，<br>而不是交出全部权限。</h3>${steps([['读取必要的输入','限定当前任务、文件或时间范围。'],['对外写入前确认','发送、下单、删除必须明确授权。'],['随时撤销','不继续调用服务，也不隐瞒已完成动作。']])}${note('服务未接入。本页的授权按钮只进入审批预览，不授予真实 OAuth 权限。',true)}${button('查看权限范围','go:CLD-10','primary')}${button('预览一次授权确认','confirm-service')}`;
case 'permissions':return `${toggle('相机使用意向','设备权限仍由浏览器另行决定','consent.camera',D.consent.camera)}${toggle('语音输入意向','不会凭此开关启动收音','consent.microphone',D.consent.microphone)}${toggle('任务提示意向','暂不申请远程推送权限','consent.notifications',D.consent.notifications)}${row('授权操作记录','本机偏好和确认历史','CLD-16','history')}${note('关闭意向不是撤销浏览器已经授予的权限；设备权限应在浏览器管理。这里不把本机偏好伪装成系统授权。')}`;
case 'schedules':return `${note('周期安排只保存为本机草稿。没有调度服务器，网页关闭后不会执行。',true)}${D.schedules.length?D.schedules.map(x=>row(x.name,`${x.frequency} ${x.time} · ${x.timezone} · 未启用`,'CLD-12','clock')).join(''):'<div class="s-hero"><h3>还没有周期任务</h3><p>把经常做的事，写成一个清楚的约定。</p></div>'}${button('新增周期任务草稿','go:CLD-12','primary')}`;
case 'schedule-edit':return `${field('任务名称','scheduleName',getDraft('CLD-12','整理这一周的想法'))}${select('频率','scheduleFrequency',['每周五','每周一','每天'],'每周五')}${field('执行时间','scheduleTime','09:00','','time')}${select('时区','scheduleTimezone',['Asia/Shanghai','America/Los_Angeles','UTC'],'Asia/Shanghai')}${note('来源：当前笔记。目标：本机整理稿。此设置尚未交给云端调度器。')}${button('保存草稿，不启用','save-schedule','primary')}`;
case 'timeline':return S.events.length?S.events.map(e=>row(e.title,new Date(e.at).toLocaleString('zh-CN')+' · '+e.body,e.task==='cloud'?'CLD-03':e.task==='photo'?'IMG-02':'DOC-02','history')).join(''):'<h3>还没有活动记录</h3>';
case 'devices':return `${row('当前浏览器','本机资料可用 · 不是云端设备认证','','cloud')}${row('其他设备','未连接，没有跨设备同步','','arrow')}${note('正式版需要设备授权、加密状态同步和撤销会话能力。不会声称另一台手机已经可以接续。',true)}${button('先导出本机备份','backup','primary')}${row('恢复已有备份','从文件迁移本机状态','CLD-17','download')}`;
case 'usage':return `<div class="s-metric">— <small>无真实账单</small></div><p>未连接计量服务。这里展示预算设计，不显示虚构额度余额。</p><div class="s-split"><div class="s-stat"><b>—</b><small>图像生成用量</small></div><div class="s-stat"><b>—</b><small>任务运行时长</small></div></div>${field('本机预算草稿（不是扣款）','budget',getDraft('CLD-15'),'例如：每周 10 次生成')}${button('保存预算草稿','save-budget')}${row('查看额度不足状态','不影响本机编辑与草稿保存','ERR-04','arrow')}`;
case 'audit':return `${note('这是本机交互审计，不是服务端不可篡改审计。')}${D.audit.length?D.audit.map(e=>row(e.title,new Date(e.at).toLocaleString('zh-CN')+' · '+e.detail,'','history')).join(''):row('还没有新的记录','改变一个权限偏好或完成一次确认','','history')}`;
case 'snapshots':case 'storage':return `<h3>资料属于你。</h3><p>可以导出、迁移，也可以删除。文件包含照片和笔记，分享前请检查。</p><div class="s-split"><div class="s-stat"><b>${Math.round(new Blob([JSON.stringify(S),JSON.stringify(D)]).size/1024)} KB</b><small>序列化工作数据</small></div><div class="s-stat"><b>${S.photo.versions.length}</b><small>图片版本</small></div></div>${button('导出完整 JSON 备份','backup','primary')}${button('选择备份并校验恢复','restore')}${note('恢复前检查格式与大小，通过后还需要确认。被恢复的周期任务仍保持未启用。')}${row('查看本机文件','照片、笔记与整理结果','DOC-01','note')}`;
case 'calendar':{const d=new Date();d.setMonth(d.getMonth()+monthOffset,1);const y=d.getFullYear(),m=d.getMonth(),n=new Date(y,m+1,0).getDate(),offset=(d.getDay()+6)%7;return `<div class="s-day-banner"><button data-action="ui:month:-1" aria-label="上个月">‹</button><span>${y} / ${String(m+1).padStart(2,'0')}<small>本机日程草稿</small></span><button data-action="ui:month:1" aria-label="下个月">›</button></div><div class="s-calendar">${'一二三四五六日'.split('').map(x=>'<span>'+x+'</span>').join('')}${'<span></span>'.repeat(offset)}${Array.from({length:n},(_,i)=>`<button data-action="ui:day:${i+1}" class="${selectedDay===i+1?'active':''}">${i+1}</button>`).join('')}</div>${D.calendar.length?D.calendar.map(e=>row(e.title,e.date+' '+e.time+' · 本机草稿','DAY-02','clock')).join(''):note('暂无已保存日程。这里没有读取系统或 Google 日历。')}${button('新增本机日程','go:DAY-02','primary')}`;}
case 'event-detail':return `${field('标题','eventTitle',getDraft('DAY-02'),'给这个时间留个名字')}${field('日期','eventDate',new Date().toLocaleDateString('en-CA'),'','date')}${field('开始时间','eventTime','10:00','','time')}${area('备注','eventNote','', '关联的事情、材料或准备项')}${note('保存为本机草稿，不发送邀请，也不写入任何外部日历。')}${button('保存日程草稿','save-event','primary')}`;
case 'contacts':return `${field('搜索示例联系人','contactSearch','', '按名字搜索') }<div id="contactResults">${fixtures.contacts.map(([n,x])=>`<button class="s-row" data-action="ui:contact:${n}"><span class="s-avatar">${n[0]}</span><span class="grow"><b>${n}</b><small>${x} · 示例联系人</small></span><span class="chev">›</span></button>`).join('')}</div>${note('这里没有读取通讯录，所有名字均为界面示例。',true)}`;
case 'messages':return `${fixtures.contacts.slice(0,2).map(([n])=>`<button class="s-row" data-action="ui:contact:${n}"><span class="s-avatar">${n[0]}</span><span class="grow"><b>${n}</b><small>可以先把方案草稿发过来。 · 示例消息</small></span><span class="muted">示例</span></button>`).join('')}${D.localOutbox.length?note('有 '+D.localOutbox.length+' 条消息被确认到本机预览记录，均未真实发送。'):note('没有连接真实消息服务，不会读取你的会话。',true)}`;
case 'thread':return `${message((D.selectedContact||'小林')+' · 示例消息','可以先把方案草稿给我看看。')}${D.localOutbox.slice(-4).map(m=>message('你 · 本机预览，未发送',m.text)).join('')}${area('消息草稿','message',D.messageDraft,'输入要表达的内容…')}${note('发送动作使用明确确认。当前只能写入本机预览记录，不能真正联系任何人。',true)}${button('审阅草稿并模拟确认','confirm-message','primary')}${row('查看引用资料','选定版本，不在发送时悄悄替换','DOC-01','picture')}`;
case 'dialer':return `<div class="s-number" id="suiteDialNumber">${esc(D.dial)||'输入号码'}</div><div class="s-keypad">${'123456789*0#'.split('').map((n,i)=>`<button data-action="ui:dial:${n}">${n}<small>${['','ABC','DEF','GHI','JKL','MNO','PQRS','TUV','WXYZ','','+',''][i]}</small></button>`).join('')}</div><div class="s-actions">${button('退格','dial-back')}${button('通话预览','confirm-call','primary')}</div>${row('来电界面','只切换 UI 状态','DAY-07','talk')}${note('没有电话服务，也不使用 tel: 自动拨打。',true)}`;
case 'incoming':return `<div class="s-hero"><span class="s-flow-tag">来电 UI 预览</span><div class="s-avatar s-hero-avatar">林</div><div class="s-title-large">小林</div><p>示例联系人 · 没有真实来电</p></div><div class="s-actions">${button('拒接预览','decline-call','danger')}${button('接听预览','go:DAY-08','primary')}</div>${row('转为消息草稿','不自动给对方发消息','DAY-05','talk')}`;
case 'call':return `<div class="s-hero"><div class="s-avatar s-hero-avatar">林</div><h3>通话状态预览</h3><p>00:00 · 未建立真实连接</p></div><div class="s-call-actions"><button data-action="ui:call-mute" class="${callMuted?'on':''}">${icon('mic')}<span>${callMuted?'已静音预览':'静音'}</span></button><button data-action="ui:call-speaker" class="${callSpeaker?'on':''}">${icon('play')}<span>扬声器</span></button><button data-action="ui:go:DAY-06">${icon('list')}<span>拨号键盘</span></button></div>${button('结束通话预览','end-call','danger')}${note('状态开关不操作真实音频线路。',true)}`;
case 'music':return `<div class="s-album">CALM<small>LOCAL UI SESSION</small></div><h3 style="text-align:center;margin-bottom:4px">潮汐之后</h3><p style="text-align:center;font-size:11px">界面示例 · 未接入音乐服务</p><div class="s-track"><i style="width:28%"></i></div><div class="compare-labels"><span>预览进度</span><span>不播放真实歌曲</span></div><div class="s-music-controls"><button data-action="ui:music-prev" aria-label="上一曲预览">‹</button><button class="big" data-action="ui:music-toggle" aria-label="切换播放预览">${D.musicPlaying?'Ⅱ':'▷'}</button><button data-action="ui:music-next" aria-label="下一曲预览">›</button></div>${note('封面动作和播放按钮共享同一个本机播放预览状态。')}`;
case 'alarm':return `${D.alarms.map((a,i)=>`<button class="s-row" data-action="ui:alarm-toggle:${i}"><span class="grow"><b style="font-size:29px;font-weight:250">${a.time}</b><small>${esc(a.label)} · ${esc(a.repeat)}</small></span><span class="s-switch ${a.enabled?'on':''}"></span></button>`).join('')}${field('新增时间','alarmTime','08:00','','time')}${button('保存闹钟草稿','save-alarm','primary')}${note('网页关闭后不会响铃，也没有创建系统闹钟。启用开关仅保存你的设计偏好。',true)}`;
case 'navigation':return `<div class="s-map"><div class="s-route-line"></div><i class="start"></i><i class="end"></i><span class="map-label">抽象路线示意 · 非真实地图</span></div>${field('起点','routeStart','示例起点')}${field('终点','routeEnd','示例终点')}${row('步行方案','预计时间、距离待地图服务返回','','arrow')}${row('公共交通方案','班次与票价需要实时服务','','clock')}${note('不请求定位，不提供真实导航或路线时长。',true)}${button('保存路线草稿','save-route')}`;
case 'reader':return `<div class="s-label">本地示例文章</div><div class="s-document">${esc(fixtures.article)}</div>${button('引用到笔记','quote-article','primary')}${row('继续讨论这篇内容','提供来源与引用范围','AI-01','talk')}`;
case 'search':return `${field('在本机找什么','search',D.readQuery,'试试：照片 / 云端 / 手势') }<div id="suiteSearchResults">${searchHTML(D.readQuery)}</div>${note('仅搜索界面目录和本机笔记；不是互联网搜索。')}`;
case 'settings':return `${[['氛围与显示','壁纸、色调与字号','SET-02','picture'],['手势与触觉','N9 / Sailfish 融合交互','SET-03','arrow'],['声音与提示','轻量反馈、安静模式','SET-04','mic'],['AI 与服务连接','未连接真实模型','SET-05','cloud'],['个人账户','本机资料和登录边界','SET-06','talk'],['记忆管理','查看、修改和忘记','SET-07','note'],['隐私与数据','能力授权、操作记录','SET-09','lock'],['存储与备份','导出、验证恢复','SET-10','download'],['无障碍','减少动效和替代操作','SET-11','check'],['关于与诊断','构建、能力与边界','SET-12','history']].map(a=>row(...a)).join('')}`;
case 'appearance':return `<h3>氛围，不只是一张壁纸。</h3><div class="ambiences">${[['sea','海雾'],['dusk','暮色'],['rose','夜航']].map(([id,n])=>`<button class="ambience ${id} ${S.theme===id?'on':''}" data-action="theme-${id}"><span>${n}</span></button>`).join('')}</div><p>壁纸、面板、强调色和机身一起改变。交互规则保持不变。</p>${toggle('较大文字','正文和表单字号适当放大','largeText',D.settings.largeText)}${toggle('加强文字对比','提亮正文，不使用颜色作为唯一信息','contrast',D.settings.contrast)}${button('返回活动封面查看','go:SYS-01')}`;
case 'gestures':return `${steps([['侧边向内 · 推开 / Peek','开始位置决定是系统手势；不松手可推回。'],['顶边向内 · 全局控制','通知放在事件视图，不和拉绳菜单混用。'],['底边向内 · 发起能力','保留当前任务，临时打开能力层。'],['内容下拉 · 拉绳菜单','初始阈值 68；每项 56；深拉 258 固定。'],['内容右滑 · 返回父页','确认页左滑接受、右滑取消。']])}${button('播放手势教学','demo','primary')}${toggle('显示替代操作','为无法完成手势的用户提供可点按动作','assist',D.settings.assist)}${note('阈值是本项目的初始设计参数，不是原系统的官方硬件参数。')}`;
case 'sound':return `${toggle('轻提示音','仅由用户操作触发短提示，不自动播放','core-sound',S.sound)}${toggle('安静模式偏好','不影响设备系统音量','quiet',D.settings.quiet)}<label class="s-form">提示强度草稿：<span id="volumeLabel">${D.settings.volume}%</span><input class="s-range" type="range" min="0" max="100" value="${D.settings.volume}" data-range="volume"></label>${button('试听一次本机短提示','test-sound')}${note('滑杆是 UI 偏好，不能修改系统音量；实际提示音使用安全的固定较低音量。')}`;
case 'models':return `<div class="s-env-status"><span class="s-status-dot"></span>没有连接模型</div><h3>模型可替换，<br>你的资料与任务不重来。</h3>${row('文字与规划','需要可信的服务端模型代理','','talk')}${row('图片生成','独立能力，不和本机调色混淆','','picture')}${row('语音识别','浏览器可选能力，需用户授权','','mic')}${note('UI 项目不收集 API 密钥，也不会把服务商密钥写入 HTML 或 localStorage。接入遵循 docs/engineering/ADAPTER_CONTRACTS.md。',true)}${button('查看服务接入设计','go:CLD-08','primary')}`;
case 'account':return `<div class="s-avatar s-hero-avatar">${esc(D.nickname[0]||'我')}</div>${field('本机昵称','nickname',D.nickname)}${button('保存昵称','save-account','primary')}${row('云端账户','未登录、未连接','','cloud')}${row('已授权设备','当前浏览器不是云端认证设备','CLD-14','lock')}${row('数据导出','随时迁移到自己的存储','SET-10','download')}`;
case 'memories':return `${note('只保存明确写下的偏好；生成图片、旅行计划不自动成为真实经历。')}${D.memories.length?D.memories.map((m,i)=>`<button class="s-row" data-action="ui:memory-select:${i}"><span class="grow"><b>${esc(m.text)}</b><small>${esc(m.source)} · ${m.enabled?'使用中':'已停用'}</small></span><span class="chev">›</span></button>`).join(''):row('还没有保存偏好','可以在下方明确添加','','note')}${area('新增一条明确偏好','memoryNew','', '例如：优先使用文字，不自动播放声音')}${button('保存这条偏好','add-memory','primary')}`;
case 'memory':{const m=D.memories[D.selectedMemory||0];return m?`<div class="s-label">来源：${esc(m.source)}</div>${area('明确的偏好','memoryText',m.text)}${toggle('允许使用这条偏好','关闭不会删除原始记录','memory-enabled',m.enabled)}${button('保存修改','save-memory','primary')}${button('忘记这条偏好','go:ERR-08','danger')}${note('删除不等于撤销已经完成的操作；这里还没有任何外部模型使用记录。')}`:note('这条偏好已不存在。')+button('回到记忆列表','go:SET-07');}
case 'privacy':return `${row('能力权限','浏览器权限和本机偏好分开','CLD-10','lock')}${row('输入资料','照片与笔记不自动上传','DOC-01','note')}${row('明确记忆','可查看、修改和忘记','SET-07','history')}${row('操作记录','查看本机动作、审批和许可变更','CLD-16','list')}${row('备份与迁移','透明格式，自行保管','SET-10','download')}${note('默认零网络请求，无分析遥测，无外部字体和脚本。不声称浏览器存储提供生产级加密。')}`;
case 'accessibility':return `${toggle('减少动效','取消装饰动画并缩短过渡','core-reduce',S.reduce)}${toggle('较大文字','针对正文和输入区放大','largeText',D.settings.largeText)}${toggle('加强文字对比','让辅助文字更容易辨认','contrast',D.settings.contrast)}${toggle('替代操作按钮','可点按返回、回主屏与菜单','assist',D.settings.assist)}<h3>键盘也能操作</h3><p>H 活动任务 · E 事件 · A 能力层 · T 系统控制 · M 拉绳菜单 · Esc 返回。输入时不拦截正文。</p>${note('已提供基础键盘与语义支持；读屏及真实设备仍需要独立验收，不能当成已经通过无障碍认证。')}`;
case 'about':return `<div class="s-hero"><span class="s-flow-tag">SWIPE / AI</span><div class="s-title-large">交互先行。<br>状态真实。</div></div>${row('UI 项目版本',window.UI_MANIFEST.version,'','check')}${row('界面目录',catalog.length+' 个已登记页面','','list')}${row('设计基线','用户认可的 V3 · 不是单一系统复刻','','history')}${note('这是独立 UI 仓库，不包含可部署 Android ROM、云手机后端、真实模型或第三方服务。')}${button('打开全界面目录','catalog')}${button('导出当前诊断摘要','export-diagnostics')}`;
case 'offline':return stateBody('offline');case 'failure':return stateBody('error');case 'empty':return stateBody('empty');case 'loading':return stateBody('loading');
case 'denied':return `<div class="s-hero"><div class="s-warning-symbol">⊘</div><h3>这项能力还不能使用。</h3><p>没有相机权限，也能选取已有照片。</p></div>${note('这是权限被拒的 UI 预览，不是浏览器当前权限查询结果。',true)}${button('改为导入照片','import','primary')}${row('查看授权说明','不要反复弹窗施压','CLD-10','lock')}${button('返回当前照片','go:IMG-02')}`;
case 'quota':return `<div class="s-hero"><div class="s-warning-symbol">—</div><h3>本次额度不足</h3><p>先留住草稿和输入，避免丢失工作。</p></div>${note('示例状态：未连接账单服务，也没有真实费用或支付操作。',true)}${button('保留草稿，稍后处理','save-for-later','primary')}${row('查看用量设计','真实费用必须由服务端提供','CLD-15','list')}${row('继续本机编辑','不受生成额度影响','IMG-02','picture')}`;
case 'pending':return `${note('这项对外动作需要一次明确的确认。最小化、退出和超时都不代表同意。',true)}${row('拟执行的动作','发送固定版本的封面','AI-05','picture')}${row('动作状态','等待确认，尚未执行','','clock')}${button('查看范围再决定','go:AI-05','primary')}${button('暂不执行','save-for-later')}`;
case 'delete':return `<div class="s-label">删除一条偏好 / 不是清空全部数据</div><h3>忘记这条，<br>其他内容仍保留。</h3><div class="s-memory"><p>${esc(D.memories[D.selectedMemory||0]?.text||'没有可删除的偏好')}</p></div>${note('删除后不会影响原始照片、笔记或其他偏好。本次会话提供一次撤销入口。')}${button('进入手势确认','confirm-delete','danger')}${button('保留，返回记忆','go:SET-07')}${lastDeleted?button('撤销上一次删除','undo-delete'):''}`;
default:return `<h3>${esc(r.name)}</h3>${note('这个路由应由对应的系统适配器显示。')}${button('返回活动任务','go:SYS-01')}`;
}
}
function stateBody(state){const m={empty:['这里还很安静。','你可以从一句话、一张照片或一份资料开始。','开始写一点','go:DOC-02'],loading:['内容正在准备。','这是加载状态设计检查。允许取消，不让用户无期限等待。','停止加载预览','reset-state'],error:['这一步没有完成。','保留已有输入和草稿。真实错误需要提供失败阶段与是否安全重试。','返回重试入口','go:AI-04'],offline:['连接暂时断开。','本机照片、笔记和偏好仍可用。联网任务应等待确认重试。','继续本机编辑','go:IMG-02']}[state];return `<div class="s-hero">${state==='loading'?'<div class="s-spinner"></div>':'<div class="s-warning-symbol">'+({empty:'○',error:'!',offline:'⌁'}[state]||'○')+'</div>'}<div class="s-title-large">${m[0]}</div><p>${m[1]}</p></div>${state==='loading'?'<div class="s-skeleton"></div><div class="s-skeleton" style="width:73%"></div><div class="s-skeleton" style="width:90%"></div>':''}${button(m[2],m[3],'primary')}${note('这是一项界面状态检查，不会修改浏览器的真实网络或任务状态。')}`;}
function searchHTML(q){const rs=PhoneModel.search(catalog,S.notes,q);return rs.length?rs.map(x=>row(x.title,x.detail,x.id,x.type==='note'?'note':'arrow')).join(''):note(q?'没有找到匹配的本机内容。':'输入词语，找回一件事。');}
function emit(){window.dispatchEvent(new CustomEvent('ui:route',{detail:{id:activeRoute,state:viewState}}));}
function rerender(){const el=$('stackRoot').lastElementChild?.querySelector('.suite-scroll')||$('surfaceContent').querySelector('.suite-scroll'),pos=el?.scrollTop||0;if(rootForTask.has(currentTask))renderRoot();renderStack();const now=$('stackRoot').lastElementChild?.querySelector('.suite-scroll')||$('surfaceContent').querySelector('.suite-scroll');if(now)now.scrollTop=pos;applyPrefs();persist();emit();}
function ensureTask(r){const key='ui-'+r.id;if(!NAMES[key]){NAMES[key]=r.name;S.messages[key]=[];S.drafts[key]='';rootForTask.set(key,r.id);addCover(key,r);}return key;}
function addCover(key,r){const wrap=document.querySelector('.home-covers');if(document.querySelector(`[data-task="${key}"]`))return;wrap.classList.add('suite-expanded');const el=document.createElement('div');el.className='cover suite-cover';el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label',r.name+' 活动封面');el.dataset.task=key;el.innerHTML=`<div class="cover-under" id="under-${key}"></div><div class="cover-face" id="face-${key}"><div class="overline">${esc(r.group)} / ${r.mode==='local'?'LOCAL':'PREVIEW'}</div><strong>${esc(r.name)}</strong><div class="suite-cover-text">${esc(r.purpose)}</div><div class="cover-bottom"><small>横滑封面，直接操作</small>${icon('arrow')}</div></div>`;wrap.appendChild(el);document.querySelector('#homePage .page-sub').textContent=wrap.children.length+' 件事，留在你离开的地方。';}
function go(id){
const r=routes.get(id);if(!r)return;viewState='default';$('suiteStateOverlay')?.remove();const previous=current();if(id==='AI-01'&&previous?.id!=='AI-01')D.lastContext=previous?.name||NAMES[currentTask];
if(demoRunning)stopDemo();if(overlay)closeOverlay(true);locked=sleeping=false;$('lock').classList.remove('visible');$('sleep').classList.remove('visible');
const special={home:()=>{minimize(false);setHome(1,false);},events:()=>{minimize(false);setHome(0,false);},capabilities:()=>{minimize(false);setHome(2,false);},controls:()=>openOverlay('top'),lock:()=>lockPhone(false),sleep:()=>lockPhone(true),photo:()=>{openTask('photo',{noAnimation:true});stack=[];renderStack();},selection:()=>{openTask('photo',{noAnimation:true});stack=[];renderStack();S.photo.selection={x:.5,y:.5,r:.23,protect:false};renderPhoto();},versions:()=>{openTask('photo',{noAnimation:true});stack=[];pushPage({kind:'history'},false);},export:()=>{openTask('photo',{noAnimation:true});stack=[];exportConfirm('photo');},notes:()=>{openTask('notes',{noAnimation:true});stack=[];renderStack();},job:()=>{openTask('cloud',{noAnimation:true});stack=[];renderStack();},focus:()=>{openTask('focus',{noAnimation:true});stack=[];renderStack();}};
if(special[r.type])special[r.type]();
else {const chain=[r];let parent=r.parent;const seen=new Set([r.id]);while(parent&&!seen.has(parent)){const p=routes.get(parent);if(!p)break;seen.add(p.id);chain.unshift(p);parent=p.parent;}
 const anchor=chain[0];let task;if(['photo','notes','job','focus'].includes(anchor.type)){task={photo:'photo',notes:'notes',job:'cloud',focus:'focus'}[anchor.type];}else task=ensureTask(anchor);
 openTask(task,{noAnimation:true});stack=chain.slice(1).map(x=>({kind:'suite',routeId:x.id}));renderRoot();renderStack();liveRouteForTask.set(task,r.id);
}
activeRoute=id;applyPrefs();syncAccess();emit();persist();
}
function showState(state){if(!['default','empty','loading','error','offline'].includes(state))return;viewState=state;$('suiteStateOverlay')?.remove();if(state!=='default'){const e=document.createElement('div');e.className='suite-state-overlay';e.id='suiteStateOverlay';e.innerHTML=stateBody(state);(appOpen?$('task'):$('screen')).appendChild(e);}emit();}
const original={renderJob,renderRoot,renderStack,menuItems,action,openTask,backPage,acceptDialog,coverAction,coverPreview,capHTML,chooseMode,pulleyPreview,resetPulley,pinPulley,finishGesture};
renderJob=function(){original.renderJob();document.querySelectorAll('[data-suite-job="percent"]').forEach(e=>e.textContent=Math.round(S.job.progress));document.querySelectorAll('[data-suite-job="meter"]').forEach(e=>e.style.width=S.job.progress+'%');document.querySelectorAll('[data-suite-job="status"]').forEach(e=>e.textContent=({idle:'等待开始',running:'正在处理原文快照',paused:'已暂停，进度保留',done:'整理已完成'})[S.job.status]);};
renderRoot=function(){const id=rootForTask.get(currentTask);if(!id)return original.renderRoot();const r=routes.get(id);$('surfaceContent').innerHTML=headerFor(r)+`<div class="suite-scroll stack-scroll" data-route-id="${r.id}">${bodyFor(r)}</div>`;renderPulley();};
renderStack=function(){original.renderStack();[...$('stackRoot').querySelectorAll('.stack-page')].forEach((el,i)=>{const p=stack[i];if(p?.kind==='suite'){const r=routes.get(p.routeId);if(r)el.innerHTML='<div class="page-dots"><span></span><span class="on"></span></div>'+headerFor(r)+`<div class="suite-scroll stack-scroll" data-route-id="${r.id}">${bodyFor(r)}</div>`;}});syncAccess();};
openTask=function(id,opt={}){original.openTask(id,{...opt,noAnimation:opt.noAnimation||rootForTask.has(id)});const custom=stack.at(-1)?.routeId;activeRoute=custom||rootForTask.get(id)||({photo:'IMG-02',notes:'DOC-02',cloud:'CLD-03',focus:'DAY-10'}[id])||activeRoute;emit();};
backPage=function(){original.backPage();activeRoute=stack.at(-1)?.routeId||rootForTask.get(currentTask)||({photo:'IMG-02',notes:'DOC-02',cloud:'CLD-03',focus:'DAY-10'}[currentTask])||'SYS-01';emit();};
function routeMenu(r){const sets={conversation:[['发送当前要求','prompt'],['查看上下文','go:AI-08'],['会话历史','go:AI-07']],generate:[['保存生成要求','generation-queue'],['查看当前照片','go:IMG-02'],['服务连接','go:SET-05']],crop:[['导出裁切副本','crop-export'],['原图对比','go:IMG-08'],['返回完整照片','go:IMG-02']],'schedule-edit':[['保存周期草稿','save-schedule'],['周期任务列表','go:CLD-11'],['查看权限','go:CLD-10']],thread:[['审阅消息草稿','confirm-message'],['引用资料','go:DOC-01'],['消息列表','go:DAY-04']],music:[[D.musicPlaying?'暂停预览':'播放预览','music-toggle'],['上一曲预览','music-prev'],['声音与提示','go:SET-04']],checklist:[['导出清单','export-checklist'],['重新提取','refresh-checklist'],['编辑原文','go:DOC-02']],memories:[['保存新偏好','add-memory'],['隐私说明','go:SET-09'],['查看审计','go:CLD-16']],settings:[['改变氛围','go:SET-02'],['隐私与数据','go:SET-09'],['关于此版本','go:SET-12']],runtime:[['查看任务','go:CLD-02'],['文件空间','go:CLD-06'],['服务连接','go:CLD-08']],contacts:[['搜索联系人','focus-field:contactSearch'],['消息列表','go:DAY-04'],['拨号预览','go:DAY-06']]};return (sets[r.type]||[['继续交代','go:AI-01'],['相关资料','go:DOC-01'],[r.parent?'返回上层':'活动任务','go:'+(r.parent||'SYS-01')]]).map(([label,a])=>({label,action:'ui:'+a,sub:'明确操作范围'}));}
menuItems=function(){const p=stack.at(-1);if(p?.kind==='suite')return routeMenu(routes.get(p.routeId));const id=rootForTask.get(currentTask);return id?routeMenu(routes.get(id)):original.menuItems();};
// Child pages use the same pull-distance selection, with their own menu behind the page.
function stackPulley(){let el=$('suiteStackPulley');if(!el){el=document.createElement('div');el.id='suiteStackPulley';el.className='pulley visible';el.style.zIndex='6';$('stackRoot').insertBefore(el,topPage());}el.innerHTML=menuItems().map((v,i)=>`<button class="pulley-row" data-action="pulley-action" data-menu="${i}"><small>0${i+1}</small>${esc(v.label)}</button>`).join('')+'<div class="pulley-hint">松手执行 · 往回推取消</div>';topPage().style.zIndex='7';return el;}
chooseMode=function(g){if(!overlay&&!locked&&!sleeping&&appOpen&&stack.at(-1)?.kind==='suite'&&!g.edge&&Math.abs(g.dy)>Math.abs(g.dx)&&g.dy>0&&g.target.tagName!=='TEXTAREA'&&(!g.scroll||g.scroll.scrollTop<=0))return 'pulley';return original.chooseMode(g);};
pulleyPreview=function(d){if(stack.at(-1)?.kind!=='suite')return original.pulleyPreview(d);const el=stackPulley(),amount=clamp(d,0,295),i=d>=68?clamp(Math.floor((d-68)/56),0,2):-1,pinned=d>=258;direct(topPage(),{transform:`translateY(${amount}px)`});[...el.querySelectorAll('.pulley-row')].forEach((e,k)=>e.classList.toggle('selected',!pinned&&k===i));if(gesture&&gesture.selected!==i){if(i>=0)feedback();gesture.selected=i;}hint(pinned?'松手固定菜单':i<0?'下拉选择，推回取消':'松手：'+menuItems()[i].label);return {i,pinned};};
resetPulley=function(animate=true){if($('suiteStackPulley')){if(topPage())(animate?animateStyle:direct)(topPage(),{transform:'translateY(0)'});$('suiteStackPulley').remove();}return original.resetPulley(animate);};
pinPulley=function(){if(stack.at(-1)?.kind!=='suite')return original.pinPulley();pulleyPinned=true;stackPulley();direct(topPage(),{transform:'translateY(230px)'});hint('菜单已展开，选择动作或推回');};
coverAction=function(id,dir){if(!rootForTask.has(id))return original.coverAction(id,dir);const r=routes.get(rootForTask.get(id));if(r.type==='music'){D.musicPlaying=!D.musicPlaying;persist();toast(D.musicPlaying?'播放状态预览已开启；没有播放真实歌曲':'播放状态已暂停');}else{persist();saveNow();toast('已保留「'+r.name+'」的本机草稿；任务没有退出');}feedback();};
coverPreview=function(id,dx){if(!rootForTask.has(id))return original.coverPreview(id,dx);const face=$('face-'+id),under=$('under-'+id);face.parentElement.classList.add('dragging');under.innerHTML=icon('check')+'<span>保留草稿 / 控制状态</span>';direct(face,{transform:`translateX(${clamp(dx,-140,140)}px)`});};
capHTML=function(){return '<div class="caps-scroll stack-scroll" style="position:relative;inset:auto">'+original.capHTML()+`<div class="suite-quick-group">更多持续能力</div>`+[['AI-01','直接交代','带着当前对象开始','talk'],['DOC-01','找回一份资料','照片、笔记与成果','note'],['CLD-01','我的个人环境','任务、授权与服务连接','cloud'],['DAY-01','安排我的一天','日程、专注与提醒草稿','clock'],['DAY-04','与人联系','消息和通话的界面预览','talk'],['DAY-09','听一会儿','音乐与封面控制预览','play'],['DAY-14','找一件事','搜索本机笔记与页面','list'],['SET-01','调整这部手机','氛围、权限和无障碍','lock']].map(([id,n,d,i])=>`<button class="cap suite-quick-cap" data-action="ui:go:${id}">${icon(i)}<span><strong>${n}</strong><small>${d}</small></span></button>`).join('')+'</div>';};
function confirm(mode,title,description,payload){pushPage({kind:'confirm',mode:'suite',suiteMode:mode,title,description,payload:JSON.parse(JSON.stringify(payload||{}))});}
acceptDialog=function(){const p=stack.at(-1);if(p?.mode!=='suite')return original.acceptDialog();if(p.consumed)return;p.consumed=true;stack.pop();renderStack();switch(p.suiteMode){case 'message':D.localOutbox.push({id:uid(),text:p.payload.text,recipient:p.payload.recipient,status:'local-preview-only'});D.messageDraft='';if(D.forms?.['DAY-05'])D.forms['DAY-05'].message='';log('消息确认预览','仅本机记录，未发送给任何人');go('DAY-05');toast('已记入本机预览，没有发送消息');break;case 'approval':log('交付动作获本机预览确认','固定版本：'+p.payload.versionId+'；未调用服务');go('AI-06');toast('确认已记录。外部动作没有执行。');break;case 'service':log('服务授权预览','未建立 OAuth 或外部连接');go('CLD-10');toast('仅记录授权预览，服务仍未连接');break;case 'delete':{const i=D.memories.findIndex(m=>m.id===p.payload.id);if(i>=0){lastDeleted={...D.memories[i]};D.memories.splice(i,1);D.selectedMemory=0;log('删除本机偏好',p.payload.id);}go('SET-07');toast('偏好已删除；到删除确认页可撤销');break;}case 'restore':if(pendingRestore){S=pendingRestore.core;D=pendingRestore.suite;S.job.status=S.job.status==='running'?'paused':S.job.status;S.focus.running=false;saveNow();persist();pendingRestore=null;location.reload();}break;case 'call':go('DAY-08');toast('只打开通话 UI，没有拨出电话');break;}persist();};
function fields(){const v={};document.querySelectorAll('#screen [data-field]').forEach(el=>{if(!el.closest('[inert]'))v[el.dataset.field]=el.value;});return v;}
function prompt(){const text=(fields().prompt||getDraft('AI-01')).trim();if(!text){toast('先输入一句要求');return;}D.messages.push({role:'user',text});let reply='当前是本机规则演示，尚未接入模型。可以记下文字、修改照片色调或整理已有笔记。';if(/^记下[:：\s]/.test(text)){const n=text.replace(/^记下[:：\s]+/,'');if(n){S.notes=(S.notes+'\n\n'+n).slice(0,30000);renderNoteCover();save();reply='已追加到本机笔记。内容和来源留在原处。';}}else if(/暖/.test(text)){applyEdit('warm');reply='已在本机调整照片暖色，新增一个版本，原图保留。';}else if(/黑白/.test(text)){applyEdit('mono');reply='已生成一个本机黑白版本，不是生成式重绘。';}else if(/(开始|继续).*整理/.test(text)){startOrResumeJob();reply='当前网页开始整理原文快照。关闭网页不会转入真实云端运行。';}else if(/暂停.*整理/.test(text)){pauseJob();reply='本机整理已暂停，进度与输入快照保留。';}else if(/发送|付款|下单/.test(text)){reply='这个请求涉及外部操作。本项目未连接对应服务，不能代替你执行；需要明确的内容和授权确认。';}D.messages.push({role:'assistant',text:reply});D.messages=D.messages.slice(-80);D.drafts['AI-01']='';if(D.forms?.['AI-01'])D.forms['AI-01'].prompt='';persist();rerender();}
function cropExport(){const c=versionCanvas(S.photo.versions[S.photo.current]),rect=PhoneModel.centerCrop(c.width,c.height,D.cropRatio),out=document.createElement('canvas');out.width=Math.round(rect.width);out.height=Math.round(rect.height);out.getContext('2d').drawImage(c,rect.x,rect.y,rect.width,rect.height,0,0,out.width,out.height);out.toBlob(b=>{if(!b)return toast('裁切导出失败');downloadBlob(b,'swipe-crop-'+D.cropRatio.replace(':','x')+'.png');log('导出中心裁切副本',D.cropRatio+'；原图未覆盖');toast('裁切 PNG 已交给浏览器下载');},'image/png');}
function backup(){downloadText(JSON.stringify({format:'ai-phone-ui-backup',version:1,core:S,suite:D},null,2),'ai-phone-ui-backup.json','application/json');log('导出本机备份','交给浏览器下载，不代表已保存到云端');toast('备份已交给浏览器下载，请妥善保管');}
function toggleValue(key){if(key.startsWith('consent.')){const k=key.split('.')[1];D.consent[k]=!D.consent[k];log('变更使用意向',k+'='+D.consent[k]+'；非浏览器授权');}else if(key==='core-sound'){S.sound=!S.sound;theme();save();}else if(key==='core-reduce'){S.reduce=!S.reduce;theme();save();}else if(key==='protect-original'){toast('原片始终保留，不允许关闭');return;}else if(key==='memory-enabled'){const m=D.memories[D.selectedMemory||0];if(m)m.enabled=!m.enabled;}else if(Object.hasOwn(D.settings,key))D.settings[key]=!D.settings[key];rerender();}
async function perform(name,param,el){const f=fields();switch(name){
case 'go':go(param);break;case 'catalog':window.dispatchEvent(new Event('ui:catalog'));break;
case 'demo':go('SYS-01');await demo();break;
case 'camera':original.action('camera');break;case 'import':original.action('import');break;case 'voice':voiceEntry();break;
case 'save-profile':D.nickname=(f.nickname||D.nickname).trim().slice(0,32)||'我的手机';persist();go('ONB-04');break;
case 'save-account':D.nickname=(f.nickname||D.nickname).trim().slice(0,32)||'我的手机';persist();toast('昵称已保存在本机');rerender();break;
case 'toggle':toggleValue(param);break;case 'prompt':prompt();break;
case 'use-transcript':D.drafts['AI-01']=f.transcribed||getDraft('AI-02');D.forms??={};D.forms['AI-01']??={};D.forms['AI-01'].prompt=D.drafts['AI-01'];go('AI-01');break;
case 'stop-preview':toast('已停止界面预览，草稿保留');go('AI-01');break;
case 'generation-queue':D.generatedDraft=(f.generationPrompt||getDraft('IMG-06')||'').trim();if(!D.generatedDraft){toast('先写下生成要求');return;}persist();go('IMG-07');break;
case 'cancel-generation':toast('队列预览已取消，要求仍然保留');go('IMG-06');break;
case 'crop-ratio':D.cropRatio=param;rerender();break;case 'crop-export':cropExport();break;
case 'gallery-select':S.photo.current=clamp(Number(param),0,S.photo.versions.length-1);renderPhoto();save();go('IMG-02');break;
case 'refresh-checklist':D.checklist=PhoneModel.extractChecklist(S.notes);rerender();toast('已从当前笔记重新提取');break;
case 'export-checklist':{const list=D.checklist.length?D.checklist:PhoneModel.extractChecklist(S.notes);downloadText(list.map(x=>`- [${x.done?'x':' '}] ${x.text}`).join('\n'),'我的清单.md');break;}
case 'export-document':downloadText(S.job.result||S.notes,'本机成果.md');log('导出文字快照');toast('文字已交给浏览器下载');break;
case 'save-transcript':if(!f.transcriptText?.trim()){toast('请先填写校对文字');return;}S.notes=(S.notes+'\n\n'+f.transcriptText).slice(0,30000);renderNoteCover();save();go('DOC-02');break;
case 'job-toggle':toggleJob();rerender();break;
case 'save-schedule':{if(!f.scheduleName?.trim()){toast('请填写任务名称');return;}D.schedules.push({id:uid(),name:f.scheduleName.trim(),time:f.scheduleTime||'09:00',frequency:f.scheduleFrequency||'每周五',timezone:f.scheduleTimezone||'Asia/Shanghai',source:'当前笔记',enabled:false});D.schedules=D.schedules.slice(-40);log('保存周期任务草稿','未启用，没有后台调度');go('CLD-11');toast('只保存了本机草稿，未启动定时任务');break;}
case 'save-budget':D.drafts['CLD-15']=f.budget||'';persist();toast('预算草稿已保存，不会产生费用');break;
case 'backup':backup();break;case 'restore':$('suiteBackupInput').click();break;
case 'month':monthOffset+=Number(param);rerender();break;case 'day':selectedDay=Number(param);rerender();break;
case 'save-event':if(!f.eventTitle?.trim()){toast('请填写日程标题');return;}D.calendar.push({id:uid(),title:f.eventTitle.trim(),date:f.eventDate||'',time:f.eventTime||'',note:f.eventNote||''});log('保存本机日程','未写入外部日历或发送邀请');go('DAY-01');toast('日程草稿已保存');break;
case 'contact':D.selectedContact=param;go('DAY-05');break;
case 'confirm-message':{const text=(f.message||D.messageDraft).trim();if(!text){toast('先填写消息草稿');return;}D.messageDraft=text;confirm('message','确认这条消息预览','固定接收方：'+(D.selectedContact||'小林')+'（示例）\n\n固定文字：'+text+'\n\n向左接受仅写入本机预览记录，不会实际发送。',{text,recipient:D.selectedContact||'小林'});break;}
case 'confirm-approval':confirm('approval','确认这次交付预览','当前版本已固定。\n\n没有任何外部服务调用，确认后仅保存本机预览记录。',{versionId:S.photo.versions[S.photo.current].id});break;
case 'confirm-service':confirm('service','确认权限预览','本次仅检查授权 UI，不代表连接任何账户或授予真实权限。',{});break;
case 'dial':D.dial=(D.dial+param).slice(0,24);if($('suiteDialNumber'))$('suiteDialNumber').textContent=D.dial;break;
case 'dial-back':D.dial=D.dial.slice(0,-1);if($('suiteDialNumber'))$('suiteDialNumber').textContent=D.dial||'输入号码';break;
case 'confirm-call':confirm('call','预览通话界面','号码：'+(D.dial||'未填写')+'\n\n不会真正拨号。这里只展示通话 UI。',{dial:D.dial});break;
case 'decline-call':go('DAY-06');toast('来电 UI 预览已关闭');break;case 'end-call':go('DAY-06');toast('通话 UI 预览已结束');break;
case 'call-mute':callMuted=!callMuted;rerender();break;case 'call-speaker':callSpeaker=!callSpeaker;rerender();break;
case 'music-toggle':D.musicPlaying=!D.musicPlaying;persist();rerender();toast('播放状态已改变，没有播放真实歌曲');break;
case 'music-prev':case 'music-next':toast('曲目切换交互预览，尚未接入音乐库');break;
case 'alarm-toggle':{const a=D.alarms[Number(param)];if(a)a.enabled=!a.enabled;persist();rerender();toast('仅保存草稿开关，不会创建系统闹钟');break;}
case 'save-alarm':if(f.alarmTime){D.alarms.push({id:uid(),time:f.alarmTime,label:'新的闹钟草稿',enabled:false,repeat:'单次'});persist();rerender();toast('闹钟草稿已保存，尚未在系统启用');}break;
case 'save-route':D.drafts['DAY-12']=JSON.stringify({from:f.routeStart,to:f.routeEnd});persist();toast('路线草稿已保存，未查询地图');break;
case 'quote-article':S.notes=(S.notes+'\n\n引用自本地示例文章：\n'+fixtures.article.slice(0,180)).slice(0,30000);save();renderNoteCover();toast('已注明来源并追加到本机笔记');break;
case 'add-memory':if(!f.memoryNew?.trim()){toast('先写下一条明确偏好');return;}D.memories.push({id:uid(),text:f.memoryNew.trim().slice(0,1000),source:'本次明确输入',enabled:true});log('新增明确偏好');rerender();break;
case 'memory-select':D.selectedMemory=Number(param);go('SET-08');break;
case 'save-memory':{const m=D.memories[D.selectedMemory||0];if(m&&f.memoryText?.trim()){m.text=f.memoryText.trim().slice(0,1000);m.source='本次明确修改';log('修改明确偏好');toast('偏好已保存');}break;}
case 'confirm-delete':{const m=D.memories[D.selectedMemory||0];if(!m){toast('没有可删除的偏好');return;}confirm('delete','确认只忘记这一条','偏好：'+m.text+'\n\n不会删除其他偏好、笔记或照片。',{id:m.id});break;}
case 'undo-delete':if(lastDeleted){D.memories.push(lastDeleted);lastDeleted=null;log('撤销删除偏好');go('SET-07');toast('已恢复这条偏好');}break;
case 'test-sound':{const old=S.sound;S.sound=true;feedback();S.sound=old;toast('已请求播放一次低音量短提示');break;}
case 'export-diagnostics':downloadText(JSON.stringify({version:UI_MANIFEST.version,screens:catalog.length,mode:'local-ui-only',remote:'not-connected',localJob:S.job.status,photoVersions:S.photo.versions.length,capabilities:{speech:!!(window.SpeechRecognition||window.webkitSpeechRecognition),fileAPI:!!window.File,localStorageAttempted:true}},null,2),'ai-phone-ui-diagnostics.json','application/json');break;
case 'focus-field':document.querySelector(`[data-field="${param}"]`)?.focus();break;
case 'reset-state':showState('default');if(current()?.type==='loading')go('SYS-01');break;
case 'save-for-later':persist();saveNow();toast('草稿保留，没有执行外部操作');go('SYS-01');break;
case 'camera-mode-record':toast('记录模式：原片保留，不生成新场景');break;
default:toast('这个动作尚未连接，输入会保留。');break;
}
}
action=async function(name,el){if(name?.startsWith('ui:')){const parts=name.slice(3).split(':');const command=parts.shift();return perform(command,parts.join(':'),el);}const result=await original.action(name,el);if(name?.startsWith('theme-')){const r=current();if(r?.type==='appearance')rerender();}return result;};
// Do not steal horizontal sliders/text editing for page gestures.
const baselineChoose=chooseMode;chooseMode=function(g){if(g.target.closest?.('input,select,[data-range]'))return 'ignore';if(g.scroll?.classList.contains('caps-scroll')&&overlay&&Math.abs(g.dy)>Math.abs(g.dx)){return 'scroll';}return baselineChoose(g);};
$('screen').addEventListener('input',e=>{const fieldName=e.target.dataset.field;if(fieldName){const id=e.target.closest('[data-route-id]')?.dataset.routeId||current()?.id||activeRoute;D.drafts[id]=e.target.value;D.forms??={};D.forms[id]??={};D.forms[id][fieldName]=e.target.value;if(fieldName==='message')D.messageDraft=e.target.value;if(fieldName==='search'){D.readQuery=e.target.value;$('suiteSearchResults').innerHTML=searchHTML(e.target.value);}if(fieldName==='contactSearch'){const q=e.target.value.toLowerCase();$('contactResults').innerHTML=fixtures.contacts.filter(x=>x[0].toLowerCase().includes(q)).map(([n,x])=>`<button class="s-row" data-action="ui:contact:${n}"><span class="s-avatar">${n[0]}</span><span class="grow"><b>${n}</b><small>${x}</small></span></button>`).join('')||note('没有匹配的示例联系人。');}persist();}
if(e.target.dataset.range==='compare'){D.comparison=Number(e.target.value);$('suiteComparison')?.style.setProperty('--compare',D.comparison+'%');persist();}if(e.target.dataset.range==='volume'){D.settings.volume=Number(e.target.value);$('volumeLabel').textContent=D.settings.volume+'%';persist();}});
$('screen').addEventListener('change',e=>{if(e.target.dataset.checkId!==undefined){if(!D.checklist.length)D.checklist=PhoneModel.extractChecklist(S.notes);const item=D.checklist[Number(e.target.dataset.checkId)];if(item)item.done=e.target.checked;persist();}});
const backupInput=document.createElement('input');backupInput.id='suiteBackupInput';backupInput.type='file';backupInput.accept='application/json,.json';backupInput.hidden=true;document.body.appendChild(backupInput);backupInput.addEventListener('change',async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>12*1024*1024){toast('备份超过 12 MB，请选择有效的小型备份');return;}try{const b=JSON.parse(await f.text());if(b.format!=='ai-phone-ui-backup'||b.version!==1)throw Error('不是本项目支持的备份格式');const core=validate(b.core),suite=PhoneModel.validate(b.suite);pendingRestore={core,suite};confirm('restore','恢复本机资料','文件已通过基本结构校验。\n这会替换当前照片、笔记、偏好与草稿。请先导出当前资料。\n\n恢复后不会启动任何周期任务。',{name:f.name});}catch(err){pendingRestore=null;toast('无法恢复：'+err.message);}});
const assist=document.createElement('div');assist.className='suite-assist';assist.id='suiteAssist';assist.innerHTML='<button data-action="back">返回</button><button data-action="ui:go:SYS-01">活动任务</button><button data-action="topmenu">系统控制</button>'; $('screen').appendChild(assist);
// Extra line icons are built-in, not fetched assets.
const defs=document.querySelector('svg defs');for(const [id,path] of [['list','M4 6h16M4 12h16M4 18h16'],['lock','M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5z'],['download','M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4'],['history','M4 10a8 8 0 1 1 0 6M4 4v6h6M12 7v6l4 2'],['trash','M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15']])if(!document.getElementById('i-'+id))defs.insertAdjacentHTML('beforeend',`<symbol id="i-${id}" viewBox="0 0 24 24"><path d="${path}"/></symbol>`);
function refreshEntrypoints(){if(!ready){setTimeout(refreshEntrypoints,40);return;}$('capsList').innerHTML=$('launcherList').innerHTML=capHTML();const top=$('topMenu');if(!top.querySelector('[data-action="ui:go:SET-01"]'))top.insertAdjacentHTML('beforeend','<button class="settings-row" style="position:absolute;left:26px;right:26px;bottom:57px;width:calc(100% - 52px)" data-action="ui:go:SET-01">所有设置 <small>进入完整设置</small></button>');applyPrefs();}
window.Suite={go,showState,current:()=>({id:current()?.id||activeRoute,route:current(),viewState}),catalog,bodyFor,perform,rerender,backup,state:()=>D,refreshEntrypoints};
refreshEntrypoints();
})();
