/* Developer-facing navigation, outside the phone. All screens share the live shell. */
(function(){
'use strict';
const manifest=UI_MANIFEST,catalog=UI_CATALOG;
const groups=[...new Set(catalog.map(r=>r.group))];
let filter='',modalOpen=false;
const originalHashId=new URLSearchParams(location.hash.replace(/^#/, '')).get('screen');
const intro=document.querySelector('.intro'),guide=document.querySelector('.guide');
intro.innerHTML=`<div class="wb-heading"><span>完整界面目录</span><small>${catalog.length} SCREENS / ${manifest.version}</small></div><input class="wb-search" id="catalogSearch" type="search" placeholder="搜索名称、编号或能力" aria-label="搜索界面目录"><div class="wb-nav" id="catalogNav"></div><div class="wb-legend">青色点：包含本机可执行操作 · 杏色点：服务状态预览<br>此目录是设计检查工具，不是手机桌面。</div>`;
// Keep the original gesture monitor IDs: the V3 engine reports actual gestures here.
guide.innerHTML=`<div class="kicker">SCREEN / INTERACTION</div><div class="guide-title" id="specTitle">活动任务</div><div class="wb-purpose" id="specPurpose"></div><div class="wb-mode" id="specMode"></div><div class="wb-spec-line"><label>ENTRY / 进入</label><span id="specEntry"></span></div><div class="wb-spec-line"><label>LEAVE / 离开</label><span id="specLeave"></span></div><div class="wb-spec-line"><label>STATE / 状态检查</label><div class="wb-state-row"><select id="viewState" aria-label="切换界面状态"><option value="default">默认状态</option><option value="empty">空内容</option><option value="loading">加载中</option><option value="error">执行失败</option><option value="offline">离线</option></select></div><span style="font-size:10px;color:#86aeb8">只检查视觉与恢复入口，不伪造网络或执行状态。</span></div><div class="wb-spec-line"><label>FLOWS / 走完一件事</label><button class="wb-flow" data-action="ui:go:IMG-01">拍摄 → 修改 → 版本 → 导出<span>IMG-01 → 02 → 03 → 09</span></button><button class="wb-flow" data-action="ui:go:AI-01">交代 → 计划 → 授权 → 结果<span>AI-01 → 04 → 05 → 06</span></button><button class="wb-flow" data-action="ui:go:DOC-02">记下 → 整理 → 后台 → 恢复<span>DOC-02 → CLD-03 → SYS-01</span></button></div><div class="gesture-monitor"><label>LIVE GESTURE FEEDBACK</label><h3 id="monitorTitle">从边缘，把内容推开。</h3><p id="monitorText">系统和内容有不同的空间，不用找返回按钮。</p><div class="training-progress" id="trainingProgress"><i></i><i></i><i></i><i></i><i></i></div></div><div class="wb-footnote">基于已认可的 V3。完整覆盖按当前 UI 范围计，不代表真实模型、Android ROM 或第三方服务已经完成。</div>`;
const tools=document.querySelector('.web-actions');tools.innerHTML=`<span class="edition">UI WORKBENCH / ${manifest.version}</span><button data-action="ui:catalog">界面目录</button><button data-action="demo">手势演示</button><button data-action="help">操作说明</button><button data-action="fullscreen">全屏</button>`;
document.querySelector('.footer').innerHTML=`<span>${catalog.length} 个界面 · 共享同一手势系统 · 单文件离线体验</span><span>UI ONLY · NO REMOTE SERVICES CONNECTED</span>`;
const modal=document.createElement('div');modal.className='wb-catalog-modal';modal.id='catalogModal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','界面目录');modal.inert=true;modal.innerHTML='<div class="wb-modal-head"><span>完整界面目录</span><button id="closeCatalog" aria-label="关闭目录">×</button></div><input id="mobileCatalogSearch" class="wb-search" type="search" placeholder="搜索界面名称或编号" aria-label="搜索完整界面目录"><div class="wb-nav" id="mobileCatalogNav"></div><div class="wb-state-row"><label for="mobileViewState">状态检查</label><select id="mobileViewState"><option value="default">默认</option><option value="empty">空内容</option><option value="loading">加载中</option><option value="error">失败</option><option value="offline">离线</option></select></div>';document.body.appendChild(modal);
function links(){const query=filter.toLowerCase();return groups.map(group=>{const rows=catalog.filter(r=>r.group===group&&(!query||(r.id+' '+r.name+' '+r.purpose).toLowerCase().includes(query)));if(!rows.length)return '';return `<h3 class="wb-group">${esc(group)} <span>${rows.length}</span></h3>`+rows.map(r=>`<button class="wb-link" data-action="ui:go:${r.id}" data-screen-id="${r.id}"><small>${r.id}</small><span>${esc(r.name)}</span><i class="${r.mode==='local'?'local':''}"></i></button>`).join('');}).join('')||'<p class="wb-footnote">没有匹配的界面。</p>';}
function refreshNav(){const html=links();$('catalogNav').innerHTML=$('mobileCatalogNav').innerHTML=html;const id=Suite.current().id;document.querySelectorAll('[data-screen-id]').forEach(el=>el.classList.toggle('active',el.dataset.screenId===id));}
function openCatalog(){modalOpen=true;modal.classList.add('open');modal.inert=false;document.querySelector('.web').inert=true;$('mobileCatalogSearch').focus();}
function closeCatalog(){modalOpen=false;modal.classList.remove('open');modal.inert=true;document.querySelector('.web').inert=false;}
function update(id){const r=catalog.find(x=>x.id===id);if(!r)return;document.querySelectorAll('[data-screen-id]').forEach(el=>el.classList.toggle('active',el.dataset.screenId===id));$('specTitle').textContent=r.name;$('specPurpose').textContent=r.purpose;$('specMode').textContent=r.mode==='local'?'本机可操作 · 不依赖云端':'交互预览 · 外部服务未连接';$('specMode').classList.toggle('preview',r.mode!=='local');$('specEntry').textContent=r.parent?`${r.parent} ${catalog.find(x=>x.id===r.parent)?.name||''} → ${r.name}`:'活动封面 / 发起能力 / 全界面目录';$('specLeave').textContent=r.parent?'内容右滑返回父页；从侧边推开最小化整件事。':'从左右边缘推开回活动任务；半推不松手可窥视。';$('viewState').value=$('mobileViewState').value=Suite.current().viewState;try{history.replaceState(null,'','#screen='+id);}catch{}if(modalOpen)closeCatalog();window.dispatchEvent(new CustomEvent('design:route',{detail:{id}}));}
$('catalogSearch').addEventListener('input',e=>{filter=e.target.value;$('mobileCatalogSearch').value=filter;refreshNav();});$('mobileCatalogSearch').addEventListener('input',e=>{filter=e.target.value;$('catalogSearch').value=filter;refreshNav();});$('viewState').addEventListener('change',e=>Suite.showState(e.target.value));$('mobileViewState').addEventListener('change',e=>{Suite.showState(e.target.value);closeCatalog();});$('closeCatalog').addEventListener('click',closeCatalog);window.addEventListener('ui:catalog',openCatalog);window.addEventListener('ui:route',e=>update(e.detail.id));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modalOpen){closeCatalog();e.stopImmediatePropagation();}},true);
const originalFinish=finishGesture;finishGesture=function(e,cancel=false){originalFinish(e,cancel);if(!appOpen&&!overlay&&!locked&&!sleeping){const id=['SYS-02','SYS-01','SYS-03'][homeIndex];update(id);}else if(overlay)update(overlay==='top'?'SYS-04':'SYS-03');};
window.Workbench={openCatalog,closeCatalog,refreshNav,update};
refreshNav();update('SYS-01');const initialId=originalHashId;
function finish(){if(!ready){setTimeout(finish,50);return;}if(initialId&&catalog.some(r=>r.id===initialId))Suite.go(initialId);else update('SYS-01');fit();}finish();
})();
